/** @typedef {{ de: string, en: string }} Word */
/** @typedef {{ id: string, text: string, meaning: string, words: Word[] }} Sentence */

/** @type {Sentence[]} */
const SENTENCES = [
  {
    id: "s1",
    text: "Guten Morgen, wie geht es dir?",
    meaning: "Good morning, how are you?",
    words: [
      { de: "Guten", en: "good" },
      { de: "Morgen,", en: "morning," },
      { de: "wie", en: "how" },
      { de: "geht", en: "goes" },
      { de: "es", en: "it" },
      { de: "dir?", en: "to you?" },
    ],
  },
  {
    id: "s2",
    text: "Ich heiße Anna.",
    meaning: "My name is Anna.",
    words: [
      { de: "Ich", en: "I" },
      { de: "heiße", en: "am called" },
      { de: "Anna.", en: "Anna." },
    ],
  },
  {
    id: "s3",
    text: "Woher kommst du?",
    meaning: "Where do you come from?",
    words: [
      { de: "Woher", en: "from where" },
      { de: "kommst", en: "come" },
      { de: "du?", en: "you?" },
    ],
  },
  {
    id: "s4",
    text: "Ich komme aus Deutschland.",
    meaning: "I come from Germany.",
    words: [
      { de: "Ich", en: "I" },
      { de: "komme", en: "come" },
      { de: "aus", en: "from" },
      { de: "Deutschland.", en: "Germany." },
    ],
  },
  {
    id: "s5",
    text: "Kannst du mir bitte helfen?",
    meaning: "Can you please help me?",
    words: [
      { de: "Kannst", en: "can" },
      { de: "du", en: "you" },
      { de: "mir", en: "me" },
      { de: "bitte", en: "please" },
      { de: "helfen?", en: "help?" },
    ],
  },
  {
    id: "s6",
    text: "Ich verstehe das nicht.",
    meaning: "I do not understand that.",
    words: [
      { de: "Ich", en: "I" },
      { de: "verstehe", en: "understand" },
      { de: "das", en: "that" },
      { de: "nicht.", en: "not." },
    ],
  },
  {
    id: "s7",
    text: "Sprechen Sie bitte langsamer.",
    meaning: "Please speak more slowly.",
    words: [
      { de: "Sprechen", en: "speak" },
      { de: "Sie", en: "you (formal)" },
      { de: "bitte", en: "please" },
      { de: "langsamer.", en: "slower." },
    ],
  },
  {
    id: "s8",
    text: "Wo ist der Bahnhof?",
    meaning: "Where is the train station?",
    words: [
      { de: "Wo", en: "where" },
      { de: "ist", en: "is" },
      { de: "der", en: "the (masc.)" },
      { de: "Bahnhof?", en: "station?" },
    ],
  },
  {
    id: "s9",
    text: "Ich möchte einen Kaffee bestellen.",
    meaning: "I would like to order a coffee.",
    words: [
      { de: "Ich", en: "I" },
      { de: "möchte", en: "would like" },
      { de: "einen", en: "a (masc.)" },
      { de: "Kaffee", en: "coffee" },
      { de: "bestellen.", en: "to order." },
    ],
  },
  {
    id: "s10",
    text: "Wie viel kostet das?",
    meaning: "How much does that cost?",
    words: [
      { de: "Wie", en: "how" },
      { de: "viel", en: "much" },
      { de: "kostet", en: "costs" },
      { de: "das?", en: "that?" },
    ],
  },
  {
    id: "s11",
    text: "Entschuldigung, wo ist die Toilette?",
    meaning: "Excuse me, where is the toilet?",
    words: [
      { de: "Entschuldigung,", en: "excuse me," },
      { de: "wo", en: "where" },
      { de: "ist", en: "is" },
      { de: "die", en: "the (fem.)" },
      { de: "Toilette?", en: "toilet?" },
    ],
  },
  {
    id: "s12",
    text: "Heute scheint die Sonne.",
    meaning: "The sun is shining today.",
    words: [
      { de: "Heute", en: "today" },
      { de: "scheint", en: "shines" },
      { de: "die", en: "the (fem.)" },
      { de: "Sonne.", en: "sun." },
    ],
  },
  {
    id: "s13",
    text: "Wir gehen morgen ins Kino.",
    meaning: "We are going to the cinema tomorrow.",
    words: [
      { de: "Wir", en: "we" },
      { de: "gehen", en: "go" },
      { de: "morgen", en: "tomorrow" },
      { de: "ins", en: "into the" },
      { de: "Kino.", en: "cinema." },
    ],
  },
  {
    id: "s14",
    text: "Ich habe Hunger.",
    meaning: "I am hungry.",
    words: [
      { de: "Ich", en: "I" },
      { de: "habe", en: "have" },
      { de: "Hunger.", en: "hunger." },
    ],
  },
  {
    id: "s15",
    text: "Das Wetter ist heute schön.",
    meaning: "The weather is nice today.",
    words: [
      { de: "Das", en: "the (neut.)" },
      { de: "Wetter", en: "weather" },
      { de: "ist", en: "is" },
      { de: "heute", en: "today" },
      { de: "schön.", en: "nice." },
    ],
  },
  {
    id: "s16",
    text: "Ich lerne jeden Tag Deutsch.",
    meaning: "I learn German every day.",
    words: [
      { de: "Ich", en: "I" },
      { de: "lerne", en: "learn" },
      { de: "jeden", en: "every" },
      { de: "Tag", en: "day" },
      { de: "Deutsch.", en: "German." },
    ],
  },
  {
    id: "s17",
    text: "Meine Familie wohnt in Berlin.",
    meaning: "My family lives in Berlin.",
    words: [
      { de: "Meine", en: "my" },
      { de: "Familie", en: "family" },
      { de: "wohnt", en: "lives" },
      { de: "in", en: "in" },
      { de: "Berlin.", en: "Berlin." },
    ],
  },
  {
    id: "s18",
    text: "Was machst du am Wochenende?",
    meaning: "What are you doing on the weekend?",
    words: [
      { de: "Was", en: "what" },
      { de: "machst", en: "do / make" },
      { de: "du", en: "you" },
      { de: "am", en: "on the" },
      { de: "Wochenende?", en: "weekend?" },
    ],
  },
  {
    id: "s19",
    text: "Ich arbeite in einem Büro.",
    meaning: "I work in an office.",
    words: [
      { de: "Ich", en: "I" },
      { de: "arbeite", en: "work" },
      { de: "in", en: "in" },
      { de: "einem", en: "an" },
      { de: "Büro.", en: "office." },
    ],
  },
  {
    id: "s20",
    text: "Können wir uns später treffen?",
    meaning: "Can we meet later?",
    words: [
      { de: "Können", en: "can" },
      { de: "wir", en: "we" },
      { de: "uns", en: "each other" },
      { de: "später", en: "later" },
      { de: "treffen?", en: "meet?" },
    ],
  },
  {
    id: "s21",
    text: "Der Zug kommt um zehn Uhr an.",
    meaning: "The train arrives at ten o'clock.",
    words: [
      { de: "Der", en: "the (masc.)" },
      { de: "Zug", en: "train" },
      { de: "kommt", en: "comes" },
      { de: "um", en: "at" },
      { de: "zehn", en: "ten" },
      { de: "Uhr", en: "o'clock" },
      { de: "an.", en: "(arrives)." },
    ],
  },
  {
    id: "s22",
    text: "Ich trinke gerne Tee.",
    meaning: "I like to drink tea.",
    words: [
      { de: "Ich", en: "I" },
      { de: "trinke", en: "drink" },
      { de: "gerne", en: "gladly / like to" },
      { de: "Tee.", en: "tea." },
    ],
  },
  {
    id: "s23",
    text: "Hast du Zeit für mich?",
    meaning: "Do you have time for me?",
    words: [
      { de: "Hast", en: "have" },
      { de: "du", en: "you" },
      { de: "Zeit", en: "time" },
      { de: "für", en: "for" },
      { de: "mich?", en: "me?" },
    ],
  },
  {
    id: "s24",
    text: "Die Kinder spielen im Park.",
    meaning: "The children are playing in the park.",
    words: [
      { de: "Die", en: "the" },
      { de: "Kinder", en: "children" },
      { de: "spielen", en: "play" },
      { de: "im", en: "in the" },
      { de: "Park.", en: "park." },
    ],
  },
  {
    id: "s25",
    text: "Ich muss noch einkaufen gehen.",
    meaning: "I still have to go shopping.",
    words: [
      { de: "Ich", en: "I" },
      { de: "muss", en: "must" },
      { de: "noch", en: "still" },
      { de: "einkaufen", en: "shopping" },
      { de: "gehen.", en: "go." },
    ],
  },
  {
    id: "s26",
    text: "Öffnen Sie bitte das Fenster.",
    meaning: "Please open the window.",
    words: [
      { de: "Öffnen", en: "open" },
      { de: "Sie", en: "you (formal)" },
      { de: "bitte", en: "please" },
      { de: "das", en: "the (neut.)" },
      { de: "Fenster.", en: "window." },
    ],
  },
  {
    id: "s27",
    text: "Es regnet stark heute Abend.",
    meaning: "It is raining hard this evening.",
    words: [
      { de: "Es", en: "it" },
      { de: "regnet", en: "rains" },
      { de: "stark", en: "strongly / hard" },
      { de: "heute", en: "today" },
      { de: "Abend.", en: "evening." },
    ],
  },
  {
    id: "s28",
    text: "Mein Bruder liest ein Buch.",
    meaning: "My brother is reading a book.",
    words: [
      { de: "Mein", en: "my" },
      { de: "Bruder", en: "brother" },
      { de: "liest", en: "reads" },
      { de: "ein", en: "a" },
      { de: "Buch.", en: "book." },
    ],
  },
  {
    id: "s29",
    text: "Wann beginnt der Film?",
    meaning: "When does the film start?",
    words: [
      { de: "Wann", en: "when" },
      { de: "beginnt", en: "begins" },
      { de: "der", en: "the (masc.)" },
      { de: "Film?", en: "film?" },
    ],
  },
  {
    id: "s30",
    text: "Ich freue mich auf den Urlaub.",
    meaning: "I am looking forward to the vacation.",
    words: [
      { de: "Ich", en: "I" },
      { de: "freue", en: "am glad" },
      { de: "mich", en: "myself" },
      { de: "auf", en: "about / for" },
      { de: "den", en: "the" },
      { de: "Urlaub.", en: "vacation." },
    ],
  },
  {
    id: "s31",
    text: "Könnten Sie das bitte wiederholen?",
    meaning: "Could you please repeat that?",
    words: [
      { de: "Könnten", en: "could" },
      { de: "Sie", en: "you (formal)" },
      { de: "das", en: "that" },
      { de: "bitte", en: "please" },
      { de: "wiederholen?", en: "repeat?" },
    ],
  },
  {
    id: "s32",
    text: "Das Essen schmeckt sehr gut.",
    meaning: "The food tastes very good.",
    words: [
      { de: "Das", en: "the (neut.)" },
      { de: "Essen", en: "food / meal" },
      { de: "schmeckt", en: "tastes" },
      { de: "sehr", en: "very" },
      { de: "gut.", en: "good." },
    ],
  },
  {
    id: "s33",
    text: "Ich bin müde und gehe schlafen.",
    meaning: "I am tired and am going to sleep.",
    words: [
      { de: "Ich", en: "I" },
      { de: "bin", en: "am" },
      { de: "müde", en: "tired" },
      { de: "und", en: "and" },
      { de: "gehe", en: "go" },
      { de: "schlafen.", en: "to sleep." },
    ],
  },
  {
    id: "s34",
    text: "Sie arbeitet als Lehrerin.",
    meaning: "She works as a teacher.",
    words: [
      { de: "Sie", en: "she" },
      { de: "arbeitet", en: "works" },
      { de: "als", en: "as" },
      { de: "Lehrerin.", en: "teacher (f)." },
    ],
  },
  {
    id: "s35",
    text: "Wir brauchen mehr Zeit.",
    meaning: "We need more time.",
    words: [
      { de: "Wir", en: "we" },
      { de: "brauchen", en: "need" },
      { de: "mehr", en: "more" },
      { de: "Zeit.", en: "time." },
    ],
  },
  {
    id: "s36",
    text: "Bitte gib mir das Salz.",
    meaning: "Please give me the salt.",
    words: [
      { de: "Bitte", en: "please" },
      { de: "gib", en: "give" },
      { de: "mir", en: "me" },
      { de: "das", en: "the (neut.)" },
      { de: "Salz.", en: "salt." },
    ],
  },
  {
    id: "s37",
    text: "Der Laden ist schon geschlossen.",
    meaning: "The shop is already closed.",
    words: [
      { de: "Der", en: "the (masc.)" },
      { de: "Laden", en: "shop" },
      { de: "ist", en: "is" },
      { de: "schon", en: "already" },
      { de: "geschlossen.", en: "closed." },
    ],
  },
  {
    id: "s38",
    text: "Ich fahre mit dem Bus zur Arbeit.",
    meaning: "I take the bus to work.",
    words: [
      { de: "Ich", en: "I" },
      { de: "fahre", en: "ride / go" },
      { de: "mit", en: "with" },
      { de: "dem", en: "the" },
      { de: "Bus", en: "bus" },
      { de: "zur", en: "to the" },
      { de: "Arbeit.", en: "work." },
    ],
  },
  {
    id: "s39",
    text: "Magst du klassische Musik?",
    meaning: "Do you like classical music?",
    words: [
      { de: "Magst", en: "like" },
      { de: "du", en: "you" },
      { de: "klassische", en: "classical" },
      { de: "Musik?", en: "music?" },
    ],
  },
  {
    id: "s40",
    text: "Lass uns zusammen kochen.",
    meaning: "Let's cook together.",
    words: [
      { de: "Lass", en: "let" },
      { de: "uns", en: "us" },
      { de: "zusammen", en: "together" },
      { de: "kochen.", en: "cook." },
    ],
  },
  {
    id: "s41",
    text: "Ich habe meinen Schlüssel verloren.",
    meaning: "I have lost my key.",
    words: [
      { de: "Ich", en: "I" },
      { de: "habe", en: "have" },
      { de: "meinen", en: "my" },
      { de: "Schlüssel", en: "key" },
      { de: "verloren.", en: "lost." },
    ],
  },
  {
    id: "s42",
    text: "Die Stadt ist sehr lebendig.",
    meaning: "The city is very lively.",
    words: [
      { de: "Die", en: "the (fem.)" },
      { de: "Stadt", en: "city" },
      { de: "ist", en: "is" },
      { de: "sehr", en: "very" },
      { de: "lebendig.", en: "lively." },
    ],
  },
  {
    id: "s43",
    text: "Er spielt gerne Fußball.",
    meaning: "He likes to play soccer.",
    words: [
      { de: "Er", en: "he" },
      { de: "spielt", en: "plays" },
      { de: "gerne", en: "gladly / likes to" },
      { de: "Fußball.", en: "soccer." },
    ],
  },
  {
    id: "s44",
    text: "Wir treffen uns vor dem Museum.",
    meaning: "We are meeting in front of the museum.",
    words: [
      { de: "Wir", en: "we" },
      { de: "treffen", en: "meet" },
      { de: "uns", en: "each other" },
      { de: "vor", en: "in front of" },
      { de: "dem", en: "the" },
      { de: "Museum.", en: "museum." },
    ],
  },
  {
    id: "s45",
    text: "Ich schreibe eine E-Mail an meinen Chef.",
    meaning: "I am writing an email to my boss.",
    words: [
      { de: "Ich", en: "I" },
      { de: "schreibe", en: "write" },
      { de: "eine", en: "an" },
      { de: "E-Mail", en: "email" },
      { de: "an", en: "to" },
      { de: "meinen", en: "my" },
      { de: "Chef.", en: "boss." },
    ],
  },
  {
    id: "s46",
    text: "Bitte warte einen Moment.",
    meaning: "Please wait a moment.",
    words: [
      { de: "Bitte", en: "please" },
      { de: "warte", en: "wait" },
      { de: "einen", en: "a" },
      { de: "Moment.", en: "moment." },
    ],
  },
  {
    id: "s47",
    text: "Das Problem ist nicht so schwierig.",
    meaning: "The problem is not so difficult.",
    words: [
      { de: "Das", en: "the (neut.)" },
      { de: "Problem", en: "problem" },
      { de: "ist", en: "is" },
      { de: "nicht", en: "not" },
      { de: "so", en: "so" },
      { de: "schwierig.", en: "difficult." },
    ],
  },
  {
    id: "s48",
    text: "Morgen fahren wir an den See.",
    meaning: "Tomorrow we are going to the lake.",
    words: [
      { de: "Morgen", en: "tomorrow" },
      { de: "fahren", en: "drive / go" },
      { de: "wir", en: "we" },
      { de: "an", en: "to" },
      { de: "den", en: "the" },
      { de: "See.", en: "lake." },
    ],
  },
  {
    id: "s49",
    text: "Ich kenne diese Straße nicht.",
    meaning: "I do not know this street.",
    words: [
      { de: "Ich", en: "I" },
      { de: "kenne", en: "know" },
      { de: "diese", en: "this" },
      { de: "Straße", en: "street" },
      { de: "nicht.", en: "not." },
    ],
  },
  {
    id: "s50",
    text: "Vielen Dank für deine Hilfe.",
    meaning: "Thank you very much for your help.",
    words: [
      { de: "Vielen", en: "much" },
      { de: "Dank", en: "thanks" },
      { de: "für", en: "for" },
      { de: "deine", en: "your" },
      { de: "Hilfe.", en: "help." },
    ],
  },
  {
    id: "s51",
    text: "Die Prüfung war ziemlich leicht.",
    meaning: "The exam was fairly easy.",
    words: [
      { de: "Die", en: "the (fem.)" },
      { de: "Prüfung", en: "exam" },
      { de: "war", en: "was" },
      { de: "ziemlich", en: "fairly" },
      { de: "leicht.", en: "easy." },
    ],
  },
  {
    id: "s52",
    text: "Ich höre jeden Morgen Nachrichten.",
    meaning: "I listen to the news every morning.",
    words: [
      { de: "Ich", en: "I" },
      { de: "höre", en: "hear / listen" },
      { de: "jeden", en: "every" },
      { de: "Morgen", en: "morning" },
      { de: "Nachrichten.", en: "news." },
    ],
  },
  {
    id: "s53",
    text: "Unsere Nachbarn sind sehr freundlich.",
    meaning: "Our neighbors are very friendly.",
    words: [
      { de: "Unsere", en: "our" },
      { de: "Nachbarn", en: "neighbors" },
      { de: "sind", en: "are" },
      { de: "sehr", en: "very" },
      { de: "freundlich.", en: "friendly." },
    ],
  },
  {
    id: "s54",
    text: "Bringst du die Flaschen zurück?",
    meaning: "Are you bringing the bottles back?",
    words: [
      { de: "Bringst", en: "bring" },
      { de: "du", en: "you" },
      { de: "die", en: "the" },
      { de: "Flaschen", en: "bottles" },
      { de: "zurück?", en: "back?" },
    ],
  },
  {
    id: "s55",
    text: "Ich möchte Deutsch fließend sprechen.",
    meaning: "I want to speak German fluently.",
    words: [
      { de: "Ich", en: "I" },
      { de: "möchte", en: "would like" },
      { de: "Deutsch", en: "German" },
      { de: "fließend", en: "fluently" },
      { de: "sprechen.", en: "to speak." },
    ],
  },
  {
    id: "s56",
    text: "Der Apfel fällt nicht weit vom Stamm.",
    meaning: "The apple does not fall far from the tree.",
    words: [
      { de: "Der", en: "the (masc.)" },
      { de: "Apfel", en: "apple" },
      { de: "fällt", en: "falls" },
      { de: "nicht", en: "not" },
      { de: "weit", en: "far" },
      { de: "vom", en: "from the" },
      { de: "Stamm.", en: "trunk / tree." },
    ],
  },
  {
    id: "s57",
    text: "Kann ich bitte die Rechnung bekommen?",
    meaning: "Can I please get the bill?",
    words: [
      { de: "Kann", en: "can" },
      { de: "ich", en: "I" },
      { de: "bitte", en: "please" },
      { de: "die", en: "the" },
      { de: "Rechnung", en: "bill" },
      { de: "bekommen?", en: "get?" },
    ],
  },
  {
    id: "s58",
    text: "Im Sommer schwimmen wir oft.",
    meaning: "In summer we often swim.",
    words: [
      { de: "Im", en: "in the" },
      { de: "Sommer", en: "summer" },
      { de: "schwimmen", en: "swim" },
      { de: "wir", en: "we" },
      { de: "oft.", en: "often." },
    ],
  },
  {
    id: "s59",
    text: "Sie hat eine neue Wohnung gefunden.",
    meaning: "She has found a new apartment.",
    words: [
      { de: "Sie", en: "she" },
      { de: "hat", en: "has" },
      { de: "eine", en: "a" },
      { de: "neue", en: "new" },
      { de: "Wohnung", en: "apartment" },
      { de: "gefunden.", en: "found." },
    ],
  },
  {
    id: "s60",
    text: "Ohne dich wäre es langweilig.",
    meaning: "Without you it would be boring.",
    words: [
      { de: "Ohne", en: "without" },
      { de: "dich", en: "you" },
      { de: "wäre", en: "would be" },
      { de: "es", en: "it" },
      { de: "langweilig.", en: "boring." },
    ],
  },
];
