/**
 * Smart Learn path — CEFR academic levels A1 → C2.
 * @typedef {{ de: string, en: string }} LearnPhrase
 * @typedef {{
 *   id: string,
 *   code: string,
 *   band: "basic" | "independent" | "proficient",
 *   title: string,
 *   titleDe: string,
 *   tagline: string,
 *   description: string,
 *   canDo: string[],
 *   focus: string[],
 *   phrases: LearnPhrase[],
 *   grammar: string[],
 *   tips: string[]
 * }} LearnLevel
 */

/** @type {LearnLevel[]} */
const LEARN_LEVELS = [
  {
    id: "a1",
    code: "A1",
    band: "basic",
    title: "Beginner",
    titleDe: "Anfänger",
    tagline: "Survive everyday moments",
    description:
      "Introduce yourself, ask simple questions, and handle very familiar situations with short phrases.",
    canDo: [
      "Say your name, origin, and where you live",
      "Order food and ask for prices",
      "Understand slow, clear speech about yourself",
    ],
    focus: ["Greetings", "Numbers & time", "sein / haben", "Nominative basics"],
    grammar: [
      "Verb second position in statements",
      "Present tense of regular verbs + sein / haben",
      "der / die / das in Nominative",
      "Simple W-questions: Wer? Was? Wo? Wie?",
    ],
    tips: [
      "Learn chunks, not only single words: Ich heiße…, Ich komme aus…",
      "Speak slowly and clearly — A1 is about being understood.",
    ],
    phrases: [
      { de: "Guten Morgen!", en: "Good morning!" },
      { de: "Wie heißt du?", en: "What is your name?" },
      { de: "Ich heiße Fahad.", en: "My name is Fahad." },
      { de: "Woher kommst du?", en: "Where do you come from?" },
      { de: "Ich komme aus Pakistan.", en: "I come from Pakistan." },
      { de: "Wo wohnst du?", en: "Where do you live?" },
      { de: "Ich wohne in Berlin.", en: "I live in Berlin." },
      { de: "Wie geht’s?", en: "How are you?" },
      { de: "Mir geht’s gut, danke.", en: "I’m fine, thank you." },
      { de: "Entschuldigung!", en: "Excuse me / Sorry!" },
      { de: "Sprechen Sie Englisch?", en: "Do you speak English?" },
      { de: "Ich verstehe nicht.", en: "I don’t understand." },
      { de: "Wie viel kostet das?", en: "How much does that cost?" },
      { de: "Einen Kaffee, bitte.", en: "A coffee, please." },
      { de: "Auf Wiedersehen!", en: "Goodbye!" },
    ],
  },
  {
    id: "a2",
    code: "A2",
    band: "basic",
    title: "Elementary",
    titleDe: "Grundlegende Kenntnisse",
    tagline: "Talk about daily life",
    description:
      "Describe routines, shopping, family, and past events in simple connected language.",
    canDo: [
      "Talk about your day and free time",
      "Make simple plans and appointments",
      "Tell a short story about yesterday",
    ],
    focus: ["Daily routines", "Shopping", "Modal verbs", "Perfekt intro"],
    grammar: [
      "Modal verbs: können, müssen, wollen, möchten",
      "Accusative: den / einen / mich / dich",
      "Perfekt with haben / sein (common verbs)",
      "Separable verbs: anrufen, aufstehen, einkaufen",
    ],
    tips: [
      "Build sentences with time phrases: heute, gestern, am Wochenende.",
      "Practice Perfekt with your real day: Ich bin aufgestanden…",
    ],
    phrases: [
      { de: "Was machst du beruflich?", en: "What do you do for work?" },
      { de: "Ich arbeite als Lehrer.", en: "I work as a teacher." },
      { de: "Am Morgen stehe ich um sieben auf.", en: "In the morning I get up at seven." },
      { de: "Ich möchte einen Termin machen.", en: "I would like to make an appointment." },
      { de: "Können Sie mir helfen?", en: "Can you help me?" },
      { de: "Ich muss noch einkaufen.", en: "I still have to go shopping." },
      { de: "Gestern habe ich Deutsch gelernt.", en: "Yesterday I learned German." },
      { de: "Wir sind in die Stadt gegangen.", en: "We went into the city." },
      { de: "Das gefällt mir.", en: "I like that." },
      { de: "Wie war dein Wochenende?", en: "How was your weekend?" },
      { de: "Es war schön, aber anstrengend.", en: "It was nice but tiring." },
      { de: "Wann treffen wir uns?", en: "When are we meeting?" },
      { de: "Lass uns morgen Kaffee trinken.", en: "Let’s have coffee tomorrow." },
      { de: "Ich habe keine Zeit.", en: "I don’t have time." },
      { de: "Alles klar!", en: "All good / Got it!" },
    ],
  },
  {
    id: "b1",
    code: "B1",
    band: "independent",
    title: "Intermediate",
    titleDe: "Mittelstufe",
    tagline: "Handle real conversations",
    description:
      "Express opinions, explain plans, and manage travel, work, and unexpected situations.",
    canDo: [
      "Give reasons and mild opinions",
      "Describe experiences and hopes",
      "Follow clear standard speech on familiar topics",
    ],
    focus: ["Opinions", "Travel & work", "weil / dass", "Dative"],
    grammar: [
      "Subordinate clauses: weil, dass, wenn (verb at end)",
      "Dative: mir, dir, dem, der, den (pl)",
      "Comparative & superlative",
      "Präteritum of sein / haben / werden + modals",
    ],
    tips: [
      "Connect ideas: Ich denke, dass… / Ich lerne Deutsch, weil…",
      "Reuse connectors from Personal notes: deshalb, trotzdem, außerdem.",
    ],
    phrases: [
      { de: "Ich finde, dass das eine gute Idee ist.", en: "I think that’s a good idea." },
      { de: "Ich lerne Deutsch, weil ich in Deutschland arbeiten möchte.", en: "I learn German because I want to work in Germany." },
      { de: "Könnten Sie das bitte wiederholen?", en: "Could you please repeat that?" },
      { de: "Das ist mir wichtig.", en: "That is important to me." },
      { de: "Im Vergleich zu früher ist es einfacher.", en: "Compared to before, it is easier." },
      { de: "Ich bin damit einverstanden.", en: "I agree with that." },
      { de: "Leider kann ich nicht kommen.", en: "Unfortunately I can’t come." },
      { de: "Was schlägst du vor?", en: "What do you suggest?" },
      { de: "Meiner Meinung nach ist das fair.", en: "In my opinion that is fair." },
      { de: "Ich habe mich über das Geschenk gefreut.", en: "I was happy about the gift." },
      { de: "Wenn ich Zeit habe, gehe ich spazieren.", en: "When I have time, I go for a walk." },
      { de: "Es wäre schön, wenn du mitkommst.", en: "It would be nice if you come along." },
      { de: "Können wir das verschieben?", en: "Can we postpone that?" },
      { de: "Ich kümmere mich darum.", en: "I’ll take care of it." },
      { de: "Das macht Sinn.", en: "That makes sense." },
    ],
  },
  {
    id: "b2",
    code: "B2",
    band: "independent",
    title: "Upper Intermediate",
    titleDe: "Gute Mittelstufe",
    tagline: "Argue, explain, negotiate",
    description:
      "Discuss abstract topics, defend a viewpoint, and follow complex arguments in clear standard German.",
    canDo: [
      "Argue for and against an idea",
      "Write clear, detailed texts on your field",
      "Understand most TV news and films",
    ],
    focus: ["Debate language", "Passive", "Konjunktiv II", "Relativsätze"],
    grammar: [
      "Relative clauses: der/die/das, dem/deren…",
      "Passive voice: werden + Partizip II",
      "Konjunktiv II for polite requests & unreal wishes",
      "Noun-verb collocations and formal register",
    ],
    tips: [
      "Practice both sides: Einerseits… andererseits…",
      "Swap casual phrases for formal ones when writing emails.",
    ],
    phrases: [
      { de: "Einerseits verstehe ich das, andererseits habe ich Bedenken.", en: "On one hand I understand that; on the other I have concerns." },
      { de: "Es wäre hilfreich, wenn Sie mir die Unterlagen schicken könnten.", en: "It would be helpful if you could send me the documents." },
      { de: "Darauf möchte ich näher eingehen.", en: "I’d like to go into that in more detail." },
      { de: "Das Projekt wurde gestern vorgestellt.", en: "The project was presented yesterday." },
      { de: "Ich würde vorschlagen, dass wir die Prioritäten klären.", en: "I would suggest that we clarify priorities." },
      { de: "Im Grunde genommen geht es um Verantwortung.", en: "Basically it’s about responsibility." },
      { de: "Das Argument überzeugt mich nicht ganz.", en: "That argument doesn’t fully convince me." },
      { de: "Könnten wir einen Kompromiss finden?", en: "Could we find a compromise?" },
      { de: "Die Entscheidung, die wir getroffen haben, war notwendig.", en: "The decision we made was necessary." },
      { de: "Es kommt darauf an, wie man es betrachtet.", en: "It depends on how you look at it." },
      { de: "Ich teile Ihre Einschätzung.", en: "I share your assessment." },
      { de: "Das lässt sich so nicht verallgemeinern.", en: "That can’t be generalized like that." },
      { de: "Kurz gesagt: Wir brauchen mehr Zeit.", en: "In short: we need more time." },
      { de: "Ich bin bereit, darüber zu verhandeln.", en: "I’m ready to negotiate about that." },
      { de: "Vielen Dank für Ihre Rückmeldung.", en: "Thank you for your feedback." },
    ],
  },
  {
    id: "c1",
    code: "C1",
    band: "proficient",
    title: "Advanced",
    titleDe: "Fortgeschritten",
    tagline: "Precise, flexible, academic",
    description:
      "Express yourself fluently and spontaneously with nuance — study, career, and complex social topics.",
    canDo: [
      "Produce clear, well-structured detailed text",
      "Use language flexibly for social and professional purposes",
      "Understand demanding longer texts and implicit meaning",
    ],
    focus: ["Nuance", "Academic style", "Partizipial", "Idioms"],
    grammar: [
      "Advanced connectors: obwohl, während, indem, wodurch",
      "Nominal style for academic writing",
      "Partizip I / II as adjectives",
      "Subtle modal particles: doch, eben, wohl, halt",
    ],
    tips: [
      "Collect collocations: eine Entscheidung treffen, in Betracht ziehen.",
      "Read short opinion pieces and rewrite one paragraph in your words.",
    ],
    phrases: [
      { de: "Es gilt abzuwägen, welche Option langfristig tragfähiger ist.", en: "We need to weigh which option is more viable long-term." },
      { de: "Damit einher geht eine spürbare Veränderung der Erwartungen.", en: "That goes hand in hand with a noticeable change in expectations." },
      { de: "Ich möchte betonen, dass dies keineswegs selbstverständlich ist.", en: "I’d like to stress that this is by no means a given." },
      { de: "Unter Berücksichtigung der Umstände erscheint das vertretbar.", en: "Considering the circumstances, that seems justifiable." },
      { de: "Die These lässt sich anhand mehrerer Beispiele belegen.", en: "The thesis can be supported with several examples." },
      { de: "Es wäre verfehlt, daraus voreilige Schlüsse zu ziehen.", en: "It would be wrong to draw hasty conclusions from that." },
      { de: "In fachlicher Hinsicht bin ich anderer Meinung.", en: "From a professional standpoint I disagree." },
      { de: "Das wirft die Frage auf, wie nachhaltig der Ansatz ist.", en: "That raises the question of how sustainable the approach is." },
      { de: "Man darf nicht außer Acht lassen, dass Ressourcen begrenzt sind.", en: "One mustn’t overlook that resources are limited." },
      { de: "Die Diskussion hat sich als äußerst fruchtbar erwiesen.", en: "The discussion proved extremely fruitful." },
      { de: "Ich halte das für durchaus diskussionswürdig.", en: "I consider that quite worth discussing." },
      { de: "Darüber hinaus verdient der soziale Aspekt Beachtung.", en: "Furthermore, the social aspect deserves attention." },
      { de: "Mit anderen Worten: Der Status quo reicht nicht aus.", en: "In other words: the status quo is not enough." },
      { de: "Das Konzept bedarf einer sorgfältigen Überarbeitung.", en: "The concept needs careful revision." },
      { de: "Ich würde mich freuen, Ihre Einschätzung zu hören.", en: "I’d be glad to hear your assessment." },
    ],
  },
  {
    id: "c2",
    code: "C2",
    band: "proficient",
    title: "Mastery",
    titleDe: "Annähernd muttersprachlich",
    tagline: "Near-native control",
    description:
      "Understand virtually everything heard or read and summarize information with precision and style.",
    canDo: [
      "Express finer shades of meaning even in complex situations",
      "Reformulate and summarize across sources",
      "Use idiomatic and literary language appropriately",
    ],
    focus: ["Style & register", "Rhetoric", "Irony & tone", "Precision"],
    grammar: [
      "Stylistic variation: spoken vs written vs literary",
      "Complex embedding and elegant subordination",
      "Idioms, fixed expressions, and wordplay awareness",
      "Subtle Konjunktiv I for reported speech",
    ],
    tips: [
      "Shadow native podcasts and note 3 elegant phrases per episode.",
      "Practice summarizing an article in half the length without losing meaning.",
    ],
    phrases: [
      { de: "Das entzieht sich einer einfachen Erklärung.", en: "That defies a simple explanation." },
      { de: "Er hat den Nagel auf den Kopf getroffen.", en: "He hit the nail on the head." },
      { de: "Es wäre vermessen, Absolute zu behaupten.", en: "It would be presumptuous to claim absolutes." },
      { de: "Die Nuancen gehen in der Übersetzung mitunter verloren.", en: "The nuances are sometimes lost in translation." },
      { de: "Man könnte geneigt sein, das als Zufall abzutun.", en: "One might be inclined to dismiss that as coincidence." },
      { de: "Seine Ausführungen zeichnen sich durch Klarheit aus.", en: "His remarks are distinguished by clarity." },
      { de: "Das steht in einem gewissen Spannungsverhältnis zueinander.", en: "That stands in a certain tension with each other." },
      { de: "Ich möchte mich der Einschätzung meines Vorredners anschließen.", en: "I’d like to associate myself with the previous speaker’s assessment." },
      { de: "Unbeschadet dessen bleibt die Grundfrage offen.", en: "That notwithstanding, the fundamental question remains open." },
      { de: "Hierin liegt der eigentliche Kern des Problems.", en: "Herein lies the real core of the problem." },
      { de: "Die Darstellung ist ebenso präzise wie elegant.", en: "The presentation is as precise as it is elegant." },
      { de: "Es empfiehlt sich, den Ton der Situation anzupassen.", en: "It is advisable to adapt the tone to the situation." },
      { de: "Das lässt Raum für unterschiedliche Lesarten.", en: "That leaves room for different readings." },
      { de: "Kurz und gut: Wir stehen vor einer Wegscheide.", en: "In short: we stand at a crossroads." },
      { de: "Darauf kommt es letztlich an.", en: "That is what it ultimately comes down to." },
    ],
  },
];
