/**
 * Personal learning notes — structured for study + tap-to-speak.
 * Typos from source notes corrected where clear (e.g. morgen, geschrieben, werden).
 */

/** @typedef {{ en?: string, de: string, note?: string }} PersonalPair */
/** @typedef {{ de: string, en: string, present: string, perfect: string, future: string }} PersonalVerb */
/** @typedef {{ caption?: string, headers: string[], rows: string[][] }} PersonalTable */
/**
 * @typedef {{
 *   id: string,
 *   title: string,
 *   titleEn: string,
 *   description: string,
 *   tips?: string[],
 *   pairs?: PersonalPair[],
 *   verbs?: PersonalVerb[],
 *   tables?: PersonalTable[],
 *   examples?: PersonalPair[]
 * }} PersonalSection
 */

/** @type {PersonalSection[]} */
const PERSONAL_SECTIONS = [
  {
    id: "lass-uns",
    title: "Lass uns…",
    titleEn: "Let’s… & Let…",
    description: "Suggestions with Lass uns… and commands with Lass…",
    pairs: [
      { en: "Let’s go outside", de: "Lass uns rausgehen." },
      { en: "Let’s start", de: "Lass uns anfangen." },
      { en: "Let’s eat", de: "Lass uns essen." },
      { en: "Let’s go", de: "Lass uns gehen." },
      { en: "Let’s go home.", de: "Lass uns nach Hause gehen." },
      { en: "Let’s have a coffee.", de: "Lass uns einen Kaffee trinken." },
      { en: "Let’s practice German", de: "Lass uns Deutsch üben." },
      { en: "Let’s watch a movie", de: "Lass uns einen Film schauen." },
      { en: "Let’s meet tomorrow", de: "Lass uns morgen treffen." },
      { en: "Leave me alone", de: "Lass mich in Ruhe!" },
      { en: "Stop that / Leave it!", de: "Lass das!" },
      { en: "Let him sleep", de: "Lass ihn schlafen." },
      { en: "Let her speak", de: "Lass sie sprechen." },
      { en: "Let me help you", de: "Lass mich dir helfen." },
    ],
  },
  {
    id: "ich-verbs",
    title: "Ich + Verb",
    titleEn: "I + useful verbs",
    description: "Useful ich-forms for expressing yourself clearly.",
    pairs: [
      { en: "I realize", de: "Ich erkenne." },
      { en: "I assume", de: "Ich vermute." },
      { en: "I avoid", de: "Ich vermeide." },
      { en: "I appreciate", de: "Ich schätze." },
      { en: "I convince", de: "Ich überzeuge." },
      { en: "I recommend", de: "Ich empfehle." },
      { en: "I demand", de: "Ich fordere." },
      { en: "I achieve", de: "Ich erreiche." },
      { en: "I develop", de: "Ich entwickle." },
      { en: "I improve", de: "Ich verbessere." },
      { en: "I support", de: "Ich unterstütze." },
      { en: "I influence", de: "Ich beeinflusse." },
      { en: "I compare", de: "Ich vergleiche." },
      { en: "I prove", de: "Ich beweise." },
      { en: "I discuss", de: "Ich diskutiere." },
      { en: "I participate", de: "Ich nehme teil." },
    ],
  },
  {
    id: "time-place",
    title: "Zeit & Ort",
    titleEn: "Time & place words",
    description: "Everyday adverbs for when and where.",
    pairs: [
      { en: "today", de: "heute" },
      { en: "tomorrow", de: "morgen" },
      { en: "yesterday", de: "gestern" },
      { en: "now", de: "jetzt" },
      { en: "up / above", de: "oben" },
      { en: "down / below", de: "unten" },
      { en: "left", de: "links" },
      { en: "right", de: "rechts" },
      { en: "front / in front", de: "vorne" },
      { en: "back / behind", de: "hinten" },
      { en: "early", de: "früh" },
      { en: "late", de: "spät" },
      { en: "always", de: "immer" },
      { en: "never", de: "nie" },
      { en: "soon", de: "bald" },
      { en: "here", de: "hier" },
      { en: "there", de: "dort" },
      { en: "everywhere", de: "überall" },
      { en: "outside", de: "draußen" },
      { en: "inside", de: "drinnen" },
    ],
  },
  {
    id: "core-verbs-tenses",
    title: "Kernverben",
    titleEn: "Core verbs: Präsens · Perfekt · Futur I",
    description: "Infinitive with ich-forms in present, perfect, and future.",
    verbs: [
      { de: "gehen", en: "to go", present: "ich gehe", perfect: "ich bin gegangen", future: "ich werde gehen" },
      { de: "kommen", en: "to come", present: "ich komme", perfect: "ich bin gekommen", future: "ich werde kommen" },
      { de: "essen", en: "to eat", present: "ich esse", perfect: "ich habe gegessen", future: "ich werde essen" },
      { de: "trinken", en: "to drink", present: "ich trinke", perfect: "ich habe getrunken", future: "ich werde trinken" },
      { de: "arbeiten", en: "to work", present: "ich arbeite", perfect: "ich habe gearbeitet", future: "ich werde arbeiten" },
      { de: "lernen", en: "to learn", present: "ich lerne", perfect: "ich habe gelernt", future: "ich werde lernen" },
      { de: "studieren", en: "to study", present: "ich studiere", perfect: "ich habe studiert", future: "ich werde studieren" },
      { de: "wohnen", en: "to live", present: "ich wohne", perfect: "ich habe gewohnt", future: "ich werde wohnen" },
      { de: "kaufen", en: "to buy", present: "ich kaufe", perfect: "ich habe gekauft", future: "ich werde kaufen" },
      { de: "verkaufen", en: "to sell", present: "ich verkaufe", perfect: "ich habe verkauft", future: "ich werde verkaufen" },
      { de: "schreiben", en: "to write", present: "ich schreibe", perfect: "ich habe geschrieben", future: "ich werde schreiben" },
      { de: "lesen", en: "to read", present: "ich lese", perfect: "ich habe gelesen", future: "ich werde lesen" },
      { de: "sprechen", en: "to speak", present: "ich spreche", perfect: "ich habe gesprochen", future: "ich werde sprechen" },
      { de: "sehen", en: "to see", present: "ich sehe", perfect: "ich habe gesehen", future: "ich werde sehen" },
      { de: "hören", en: "to hear", present: "ich höre", perfect: "ich habe gehört", future: "ich werde hören" },
      { de: "finden", en: "to find", present: "ich finde", perfect: "ich habe gefunden", future: "ich werde finden" },
      { de: "helfen", en: "to help", present: "ich helfe", perfect: "ich habe geholfen", future: "ich werde helfen" },
      { de: "schlafen", en: "to sleep", present: "ich schlafe", perfect: "ich habe geschlafen", future: "ich werde schlafen" },
      { de: "fahren", en: "to drive / go", present: "ich fahre", perfect: "ich bin gefahren", future: "ich werde fahren" },
      { de: "fliegen", en: "to fly", present: "ich fliege", perfect: "ich bin geflogen", future: "ich werde fliegen" },
      { de: "laufen", en: "to run", present: "ich laufe", perfect: "ich bin gelaufen", future: "ich werde laufen" },
      { de: "bleiben", en: "to stay", present: "ich bleibe", perfect: "ich bin geblieben", future: "ich werde bleiben" },
      { de: "werden", en: "to become", present: "ich werde", perfect: "ich bin geworden", future: "ich werde werden" },
      { de: "bringen", en: "to bring", present: "ich bringe", perfect: "ich habe gebracht", future: "ich werde bringen" },
      { de: "beginnen", en: "to begin", present: "ich beginne", perfect: "ich habe begonnen", future: "ich werde beginnen" },
    ],
  },
  {
    id: "negation",
    title: "Negation",
    titleEn: "nicht & kein",
    description: "Practice nicht (with adjectives/verbs) and kein (with nouns).",
    pairs: [
      { en: "I am not tired.", de: "Ich bin nicht müde." },
      { en: "He does not work today.", de: "Er arbeitet heute nicht." },
      { en: "We are not at home.", de: "Wir sind nicht zu Hause." },
      { en: "She does not speak German.", de: "Sie spricht nicht Deutsch." },
      { en: "The coffee is not hot.", de: "Der Kaffee ist nicht heiß." },
      { en: "They are not happy.", de: "Sie sind nicht glücklich." },
      { en: "I have no car.", de: "Ich habe kein Auto." },
      { en: "She has no time.", de: "Sie hat keine Zeit." },
      { en: "We have no money.", de: "Wir haben kein Geld." },
      { en: "He drinks no coffee.", de: "Er trinkt keinen Kaffee." },
      { en: "They have no children.", de: "Sie haben keine Kinder." },
      { en: "There is no problem.", de: "Es gibt kein Problem." },
    ],
  },
  {
    id: "pronouns-possessive-nom",
    title: "Pronomen · Nominativ",
    titleEn: "Pronouns & possessive (Nominativ)",
    description: "Personal pronouns and possessive articles in Nominativ.",
    tips: ["Pattern for calling: Ich rufe dich an · Du rufst mich an."],
    tables: [
      {
        caption: "Personal pronouns",
        headers: ["Nominativ", "Akkusativ", "Dativ"],
        rows: [
          ["ich", "mich", "mir"],
          ["du", "dich", "dir"],
          ["er", "ihn", "ihm"],
          ["sie (f)", "sie", "ihr"],
          ["es", "es", "ihm"],
          ["wir", "uns", "uns"],
          ["ihr", "euch", "euch"],
          ["sie (pl)", "sie", "ihnen"],
          ["Sie", "Sie", "Ihnen"],
        ],
      },
      {
        caption: "Possessive articles — Nominativ",
        headers: ["Base", "m", "f", "n", "pl"],
        rows: [
          ["mein", "mein", "meine", "mein", "meine"],
          ["dein", "dein", "deine", "dein", "deine"],
          ["sein", "sein", "seine", "sein", "seine"],
          ["ihr", "ihr", "ihre", "ihr", "ihre"],
          ["unser", "unser", "unsere", "unser", "unsere"],
          ["euer", "euer", "eure", "euer", "eure"],
          ["Ihr", "Ihr", "Ihre", "Ihr", "Ihre"],
        ],
      },
    ],
    examples: [
      { de: "Ich rufe dich an.", en: "I call you." },
      { de: "Du rufst mich an.", en: "You call me." },
      { de: "Ich rufe euch an.", en: "I call you (pl)." },
      { de: "Ich rufe Sie an.", en: "I call you (formal)." },
      { de: "Sie rufen ihn an.", en: "They / you call him." },
      { de: "Sie rufen sie an.", en: "They call her / them." },
      { de: "Er ruft uns an.", en: "He calls us." },
      { de: "Er ruft sie an.", en: "He calls her / them." },
      { de: "Wir rufen es an.", en: "We call it." },
      { de: "Ich sehe ihn.", en: "I see him." },
      { de: "Er sieht mich.", en: "He sees me." },
      { de: "Du machst den Tee.", en: "You make the tea." },
    ],
  },
  {
    id: "possessive-akk",
    title: "Possessiv · Akkusativ",
    titleEn: "Possessive articles — Accusative",
    description: "mein/dein… change in Accusative (especially masculine: meinen).",
    tables: [
      {
        headers: ["Base", "m", "f", "n", "pl"],
        rows: [
          ["mein", "meinen", "meine", "mein", "meine"],
          ["dein", "deinen", "deine", "dein", "deine"],
          ["sein", "seinen", "seine", "sein", "seine"],
          ["ihr", "ihren", "ihre", "ihr", "ihre"],
          ["unser", "unseren", "unsere", "unser", "unsere"],
          ["euer", "euren", "eure", "euer", "eure"],
          ["Ihr", "Ihren", "Ihre", "Ihr", "Ihre"],
        ],
      },
    ],
  },
  {
    id: "possessive-dat",
    title: "Possessiv · Dativ",
    titleEn: "Possessive articles — Dative",
    description: "Dative endings: meinem, meiner, meinem, meinen.",
    tables: [
      {
        headers: ["Base", "m", "f", "n", "pl"],
        rows: [
          ["mein", "meinem", "meiner", "meinem", "meinen"],
          ["dein", "deinem", "deiner", "deinem", "deinen"],
          ["sein", "seinem", "seiner", "seinem", "seinen"],
          ["ihr", "ihrem", "ihrer", "ihrem", "ihren"],
          ["unser", "unserem", "unserer", "unserem", "unseren"],
          ["euer", "eurem", "eurer", "eurem", "euren"],
          ["Ihr", "Ihrem", "Ihrer", "Ihrem", "Ihren"],
        ],
      },
    ],
    examples: [
      { de: "Sie macht ihrem Bruder den Tee.", en: "She makes her brother the tea." },
      { de: "Ich bringe meiner Mutter die Blume.", en: "I bring my mother the flower." },
      { de: "Er bringt deinem Kind das Spielzeug.", en: "He brings your child the toy." },
      { de: "Du kaufst unseren Eltern das Geschenk.", en: "You buy our parents the gift." },
    ],
  },
  {
    id: "adj-nom",
    title: "Adjektiv · Nominativ",
    titleEn: "Adjective endings — Nominative",
    description: "With definite, indefinite/possessive, and no article.",
    tips: ["Pattern: (article + adj + Nom) + verb + Dativ + Akkusativ"],
    tables: [
      {
        caption: "With definite article",
        headers: ["Article", "Adjective"],
        rows: [
          ["der", "neue"],
          ["die", "neue"],
          ["das", "neue"],
          ["die (pl)", "neuen"],
        ],
      },
      {
        caption: "With indefinite / possessive",
        headers: ["Article", "Adjective"],
        rows: [
          ["ein / dein", "neuer"],
          ["eine / seine", "neue"],
          ["ein / ihr", "neues"],
          ["meine (pl)", "neuen"],
        ],
      },
      {
        caption: "Without article",
        headers: ["Gender", "Adjective"],
        rows: [
          ["m", "schöner"],
          ["f", "schöne"],
          ["n", "schönes"],
          ["pl", "schöne"],
        ],
      },
    ],
  },
  {
    id: "adj-akk",
    title: "Adjektiv · Akkusativ",
    titleEn: "Adjective endings — Accusative",
    description: "Only masculine changes vs Nominative with definite articles (den neuen).",
    tips: ["Pattern: Nom + verb + Dativ + (article + adj + Akkusativ)"],
    tables: [
      {
        caption: "With definite article",
        headers: ["Article", "Adjective"],
        rows: [
          ["den", "neuen"],
          ["die", "neue"],
          ["das", "neue"],
          ["die (pl)", "neuen"],
        ],
      },
      {
        caption: "With indefinite / possessive",
        headers: ["Article", "Adjective"],
        rows: [
          ["einen / deinen", "neuen"],
          ["eine / seine", "neue"],
          ["ein / ihr", "neues"],
          ["meine (pl)", "neuen"],
        ],
      },
      {
        caption: "Without article",
        headers: ["Gender", "Adjective"],
        rows: [
          ["m", "schönen"],
          ["f", "schöne"],
          ["n", "schönes"],
          ["pl", "schöne"],
        ],
      },
    ],
    examples: [
      { de: "Ich sehe den kleinen Hund.", en: "I see the small dog." },
      { de: "Ich sehe deinen kleinen Hund.", en: "I see your small dog." },
      { de: "Ich sehe kleinen Hund.", en: "I see (a) small dog. (no article)" },
      { de: "Er trägt die neue Tasche.", en: "He carries the new bag." },
      { de: "Sie trägt ihre neue Tasche.", en: "She carries her new bag." },
      { de: "Sie trägt neue Tasche.", en: "She carries (a) new bag." },
      { de: "Er kauft das neue Auto.", en: "He buys the new car." },
      { de: "Er kauft ein neues Auto.", en: "He buys a new car." },
      { de: "Er kauft neues Auto.", en: "He buys (a) new car." },
      { de: "Wir lesen die interessanten Bücher.", en: "We read the interesting books." },
      { de: "Wir lesen Ihre interessanten Bücher.", en: "We read your interesting books." },
      { de: "Wir lesen interessante Bücher.", en: "We read interesting books." },
    ],
  },
  {
    id: "adj-dat",
    title: "Adjektiv · Dativ",
    titleEn: "Adjective endings — Dative",
    description: "Dative adjective endings with and without articles.",
    tips: ["Pattern: Nom + verb + (article + adj + Dativ) + Akkusativ"],
    tables: [
      {
        caption: "With definite article",
        headers: ["Article", "Adjective"],
        rows: [
          ["dem", "neuen"],
          ["der", "neuen"],
          ["dem", "neuen"],
          ["den (pl)", "neuen"],
        ],
      },
      {
        caption: "With indefinite / possessive",
        headers: ["Article", "Adjective"],
        rows: [
          ["einem / deinem", "neuen"],
          ["einer / seiner", "neuen"],
          ["einem / ihrem", "neuen"],
          ["meinen (pl)", "neuen"],
        ],
      },
      {
        caption: "Without article",
        headers: ["Gender", "Adjective"],
        rows: [
          ["m", "schönem"],
          ["f", "schöner"],
          ["n", "schönem"],
          ["pl", "schönen"],
        ],
      },
    ],
    examples: [
      { de: "Ich helfe dem alten Mann.", en: "I help the old man." },
      { de: "Ich helfe einem alten Mann.", en: "I help an old man." },
      { de: "Ich helfe altem Mann.", en: "I help (an) old man." },
      { de: "Ich helfe der alten Frau.", en: "I help the old woman." },
      { de: "Ich helfe einer alten Frau.", en: "I help an old woman." },
      { de: "Ich helfe alter Frau.", en: "I help (an) old woman." },
      { de: "Ich helfe dem kleinen Mädchen.", en: "I help the little girl." },
      { de: "Ich helfe einem kleinen Mädchen.", en: "I help a little girl." },
      { de: "Ich helfe kleinem Mädchen.", en: "I help (a) little girl." },
      { de: "Du hast den kleinen Kindern die Schokolade gegeben.", en: "You gave the little children the chocolate." },
      { de: "Du hast seinen kleinen Kindern die Schokolade gegeben.", en: "You gave his little children the chocolate." },
      { de: "Du hast kleinen Kindern die Schokolade gegeben.", en: "You gave little children the chocolate." },
    ],
  },
  {
    id: "sentence-frames",
    title: "Satzmuster",
    titleEn: "Core sentence frames",
    description: "Quick templates for present, perfect, and modal verbs.",
    tips: [
      "Present: Nom + verb + Dativ + Akkusativ",
      "Present Perfect: Nom + haben/sein + Dativ + Akkusativ + Partizip II",
      "Modal: Nom + modal verb + Dativ + Akkusativ + infinitive",
    ],
  },
  {
    id: "separable",
    title: "Trennbare Präfixe",
    titleEn: "Separable prefixes",
    description: "ab, an, auf, aus, bei, ein, mit, nach, vor, weg, zu, zurück, zusammen, fern, um",
    tips: [
      "Present: prefix goes to the end — Er ruft seine Mutter an.",
      "Perfect: ge- sits between prefix and stem — angerufen.",
      "Modal: prefix stays on the infinitive — anrufen.",
    ],
    examples: [
      { de: "Er ruft seine Mutter an.", en: "He calls his mother.", note: "Present" },
      { de: "Er hat seine Mutter angerufen.", en: "He has called / called his mother.", note: "Present Perfect" },
      { de: "Er will seine Mutter anrufen.", en: "He wants to call his mother.", note: "Modal" },
      { de: "Er kommt an.", en: "He arrives / is arriving.", note: "Present" },
      { de: "Er ist angekommen.", en: "He has arrived / arrived.", note: "Perfect" },
      { de: "Wir laden dich ein.", en: "We invite you.", note: "Present" },
      { de: "Wir haben dich eingeladen.", en: "We have invited / invited you.", note: "Perfect" },
      { de: "Wir möchten dich einladen.", en: "We would like to invite you.", note: "Modal" },
    ],
  },
  {
    id: "inseparable",
    title: "Untrennbare Präfixe",
    titleEn: "Inseparable prefixes",
    description: "be-, emp-, ent-, er-, ge-, miss-, ver-, zer- (never split; no ge- in perfect).",
    examples: [
      { de: "Die Klasse beginnt um 20 Uhr.", en: "The class begins at 8 p.m." },
      { de: "Ich bezahle mit der Karte.", en: "I pay with the card." },
      { de: "Der Dieb entkommt.", en: "The thief escapes." },
      { de: "Der Dieb ist entkommen.", en: "The thief has escaped." },
    ],
  },
  {
    id: "reflexive",
    title: "Reflexive Verben",
    titleEn: "Reflexive verbs & pronouns",
    description: "sich waschen, sich freuen, sich interessieren, sich entscheiden, sich beeilen, sich erinnern…",
    tables: [
      {
        caption: "Reflexive pronouns",
        headers: ["Nominativ", "Akkusativ", "Dativ"],
        rows: [
          ["ich", "mich", "mir"],
          ["du", "dich", "dir"],
          ["er / sie / es", "sich", "sich"],
          ["wir", "uns", "uns"],
          ["ihr", "euch", "euch"],
          ["sie / Sie", "sich", "sich"],
        ],
      },
    ],
    tips: ["Akkusativ: Nom + verb + reflexive + …", "Dativ: when a body part / object follows — Ich wasche mir die Hände."],
    examples: [
      { de: "Ich wasche mich.", en: "I wash myself.", note: "Akkusativ" },
      { de: "Er wäscht sich.", en: "He washes himself.", note: "Akkusativ" },
      { de: "Sie freut sich über das Geschenk.", en: "She is happy about the gift.", note: "Akkusativ" },
      { de: "Wir interessieren uns für die Geschichte.", en: "We are interested in the story.", note: "Akkusativ" },
      { de: "Sie beeilen sich.", en: "They hurry / are in a hurry.", note: "Akkusativ" },
      { de: "Wir treffen uns am Montag.", en: "We meet (each other) on Monday.", note: "Akkusativ" },
      { de: "Ich wasche mir die Hände.", en: "I wash my hands.", note: "Dativ" },
      { de: "Du putzt dir die Zähne.", en: "You brush your teeth.", note: "Dativ" },
      { de: "Ich kämme mir die Haare.", en: "I comb my hair.", note: "Dativ" },
      { de: "Er wäscht sich die Hände.", en: "He washes his hands.", note: "Dativ" },
    ],
  },
  {
    id: "imperative",
    title: "Imperativ",
    titleEn: "Commands & requests",
    description: "du / ihr / Sie forms for advice and requests.",
    tips: ["du: stem (often no -st) · ihr: like present without subject · Sie: infinitive + Sie"],
    examples: [
      { de: "Geh!", en: "Go!", note: "du" },
      { de: "Iss den Apfel!", en: "Eat the apple!", note: "du" },
      { de: "Trink Milch!", en: "Drink milk!", note: "du" },
      { de: "Schlaf gut!", en: "Sleep well!", note: "du" },
      { de: "Hör zu!", en: "Listen!", note: "du · zuhören" },
      { de: "Bring mir das Wasser!", en: "Bring me the water!", note: "du" },
      { de: "Mach uns den Tee!", en: "Make us the tea!", note: "du" },
      { de: "Mach die Tür auf!", en: "Open the door!", note: "du" },
      { de: "Kauf mir das Hemd!", en: "Buy me the shirt!", note: "du" },
      { de: "Lern Deutsch!", en: "Learn German!", note: "du" },
      { de: "Lest das Buch!", en: "Read the book!", note: "ihr" },
      { de: "Lest die Zeitung!", en: "Read the newspaper!", note: "ihr" },
      { de: "Lernt Deutsch!", en: "Learn German!", note: "ihr" },
      { de: "Kauft den Kindern die Schokolade!", en: "Buy the children the chocolate!", note: "ihr" },
      { de: "Esst gesund!", en: "Eat healthily!", note: "ihr" },
      { de: "Esst die Äpfel!", en: "Eat the apples!", note: "ihr" },
      { de: "Kauft dem Lehrer das Geschenk!", en: "Buy the teacher the gift!", note: "ihr" },
      { de: "Machen Sie uns Biryani!", en: "Make us biryani!", note: "Sie" },
      { de: "Bringen Sie uns Wasser!", en: "Bring us water!", note: "Sie" },
      { de: "Machen Sie bitte die Tür zu!", en: "Please close the door!", note: "Sie" },
      { de: "Hören Sie zu!", en: "Listen!", note: "Sie · zuhören" },
      { de: "Schlafen Sie gut!", en: "Sleep well!", note: "Sie" },
      { de: "Essen Sie gesund!", en: "Eat healthily!", note: "Sie" },
    ],
  },
  {
    id: "prep-akk",
    title: "Präpositionen · Akk",
    titleEn: "Accusative prepositions",
    description: "für · durch · ohne · gegen · um · bis",
    examples: [
      { de: "Der Laptop ist für dich.", en: "The laptop is for you.", note: "für" },
      { de: "Er zahlt viel für das Auto.", en: "He pays a lot for the car.", note: "für" },
      { de: "Wir gehen durch die Stadt.", en: "We walk through the city.", note: "durch" },
      { de: "Wir gehen durch den Wald.", en: "We walk through the forest.", note: "durch" },
      { de: "Ich kann nicht ohne mein Handy leben.", en: "I can’t live without my phone.", note: "ohne" },
      { de: "Ich kann nicht ohne dich leben.", en: "I can’t live without you.", note: "ohne" },
      { de: "Er ist gegen mich.", en: "He is against me.", note: "gegen" },
      { de: "Die Kinder spielen um das Haus.", en: "The children play around the house.", note: "um" },
      { de: "Sie stehen um 8 Uhr auf.", en: "They get up at 8 o’clock.", note: "um (time)" },
      { de: "Ich warte bis morgen.", en: "I wait until tomorrow.", note: "bis" },
      { de: "Ich kann den Bericht bis morgen fertigstellen.", en: "I can finish the report by tomorrow.", note: "bis" },
    ],
  },
  {
    id: "prep-dat",
    title: "Präpositionen · Dat",
    titleEn: "Dative prepositions",
    description: "aus · bei · mit · nach · zu · seit · von · gegenüber · außer · ab",
    examples: [
      { de: "Ich komme aus Pakistan.", en: "I come from Pakistan.", note: "aus" },
      { de: "Ich trinke Wasser aus der Flasche.", en: "I drink water from the bottle.", note: "aus" },
      { de: "Der Tisch ist aus Holz gemacht.", en: "The table is made of wood.", note: "aus" },
      { de: "Ich bin bei meinem Freund.", en: "I am at my friend’s place.", note: "bei" },
      { de: "Die Apotheke ist bei dem Krankenhaus.", en: "The pharmacy is near the hospital.", note: "bei" },
      { de: "Ich bin mit meinem Freund.", en: "I am with my friend.", note: "mit" },
      { de: "Ich gehe nach Hause.", en: "I go home.", note: "nach" },
      { de: "Ich fahre nach Makkah.", en: "I travel to Makkah.", note: "nach" },
      { de: "Nach dem Essen gehen wir spazieren.", en: "After the meal we go for a walk.", note: "nach (after)" },
      { de: "Wir gehen zum Markt.", en: "We go to the market.", note: "zu dem → zum" },
      { de: "Die Kinder gehen zur Schule.", en: "The children go to school.", note: "zu der → zur" },
      { de: "Ich unterrichte Deutsch seit 2 Jahren.", en: "I have been teaching German for 2 years.", note: "seit" },
      { de: "Das Geschenk ist von meiner Mutter.", en: "The gift is from my mother.", note: "von" },
      { de: "Das Auto ist von meinem Vater.", en: "The car is from my father.", note: "von" },
      { de: "Die Schule liegt gegenüber der Uni.", en: "The school is opposite the university.", note: "gegenüber" },
      { de: "Außer mir war niemand da.", en: "Besides me, nobody was there.", note: "außer" },
      { de: "Ab morgen fange ich mit der Diät an.", en: "From tomorrow I start the diet.", note: "ab" },
      { de: "Ab nächster Stunde werde ich lernen.", en: "From next class I will study.", note: "ab" },
      { de: "Ich lerne Deutsch seit 2 Wochen.", en: "I have been learning German for 2 weeks.", note: "seit" },
    ],
  },
  {
    id: "prep-two-way",
    title: "Wechselpräpositionen",
    titleEn: "Two-way prepositions",
    description: "an · auf · hinter · in · neben · über · unter · vor · zwischen — Akk (motion) / Dat (location).",
    tips: [
      "stellen / stehen = vertical · legen / liegen = horizontal · hängen = hang",
      "Wohin? → Accusative · Wo? → Dative",
    ],
    examples: [
      { de: "Ich hänge das Bild an die Wand.", en: "I hang the picture on the wall. (motion)", note: "Wohin? Akk" },
      { de: "Das Bild hängt an der Wand.", en: "The picture hangs on the wall. (location)", note: "Wo? Dat" },
      { de: "Ich lege den Bleistift auf den Tisch.", en: "I put the pencil on the table. (motion)", note: "Wohin? Akk" },
      { de: "Der Bleistift liegt auf dem Tisch.", en: "The pencil lies on the table. (location)", note: "Wo? Dat" },
      { de: "Ich stelle den Stuhl hinter die Tür.", en: "I put the chair behind the door. (motion)", note: "Wohin? Akk" },
      { de: "Der Stuhl steht hinter der Tür.", en: "The chair stands behind the door. (location)", note: "Wo? Dat" },
      { de: "Ich lege den Kuli ins Buch.", en: "I put the pen into the book. (motion)", note: "Wohin? Akk" },
      { de: "Der Kuli liegt im Buch.", en: "The pen lies in the book. (location)", note: "Wo? Dat" },
      { de: "Der Junge stellt den Stuhl neben den Tisch.", en: "The boy puts the chair next to the table. (motion)", note: "Wohin? Akk" },
      { de: "Der Stuhl steht neben dem Tisch.", en: "The chair stands next to the table. (location)", note: "Wo? Dat" },
      { de: "Der Mann hängt die Lampe über den Tisch.", en: "The man hangs the lamp over the table. (motion)", note: "Wohin? Akk" },
      { de: "Die Lampe hängt über dem Tisch.", en: "The lamp hangs over the table. (location)", note: "Wo? Dat" },
      { de: "Das Kind legt die Schuhe unter den Tisch.", en: "The child puts the shoes under the table. (motion)", note: "Wohin? Akk" },
      { de: "Die Katze schläft unter dem Auto.", en: "The cat sleeps under the car. (location)", note: "Wo? Dat" },
      { de: "Ich lege das Sofa vor das Fenster.", en: "I put the sofa in front of the window. (motion)", note: "Wohin? Akk" },
      { de: "Die Bank liegt vor der Universität.", en: "The bench is in front of the university. (location)", note: "Wo? Dat" },
      { de: "Das Mädchen stellt den Tisch zwischen die Stühle.", en: "The girl puts the table between the chairs. (motion)", note: "Wohin? Akk" },
      { de: "Der Tisch steht zwischen den Stühlen.", en: "The table stands between the chairs. (location)", note: "Wo? Dat" },
    ],
  },
  {
    id: "comparison",
    title: "Vergleiche",
    titleEn: "Comparison",
    description: "positive · comparative (als) · superlative (am …sten / der/die/das …ste)",
    examples: [
      { de: "Mein Auto ist schnell.", en: "My car is fast.", note: "positive" },
      { de: "Mein Auto ist schneller als dein Auto.", en: "My car is faster than your car.", note: "comparative" },
      { de: "Mein Auto ist am schnellsten.", en: "My car is the fastest.", note: "superlative" },
      { de: "Mein Haus ist größer als dein Haus.", en: "My house is bigger than your house.", note: "größer" },
      { de: "Das Wasser ist kälter als gestern.", en: "The water is colder than yesterday.", note: "kälter" },
      { de: "Die Tasche ist teurer als der Rucksack.", en: "The bag is more expensive than the backpack.", note: "teurer" },
      { de: "Das Zimmer ist sauberer als die Küche.", en: "The room is cleaner than the kitchen.", note: "sauberer" },
      { de: "Mein Haus ist am größten in der Straße.", en: "My house is the biggest on the street.", note: "am größten" },
      { de: "Das Wasser ist am kältesten im Winter.", en: "The water is coldest in winter.", note: "am kältesten" },
      { de: "Die Tasche ist am teuersten in dem Laden.", en: "The bag is the most expensive in the shop.", note: "am teuersten" },
      { de: "Das Zimmer ist am saubersten nach dem Putzen.", en: "The room is cleanest after cleaning.", note: "am saubersten" },
    ],
  },
  {
    id: "genitiv",
    title: "Genitiv",
    titleEn: "Genitive case",
    description: "Belonging: des/der/eines/einer… and name genitive.",
    tips: [
      "Masculine/neuter often add -(e)s: des Hauses, des Kindes, des Mädchens.",
      "Feminine/plural: der — der Mutter, der Eltern.",
      "von + Dativ is a common spoken alternative: das Auto von dem Vater.",
    ],
    tables: [
      {
        caption: "Articles in Genitive",
        headers: ["", "Definite", "Indefinite"],
        rows: [
          ["m", "des", "eines"],
          ["f", "der", "einer"],
          ["n", "des", "eines"],
          ["pl", "der", "—"],
        ],
      },
    ],
    examples: [
      { de: "Das Auto des Vaters.", en: "The father’s car." },
      { de: "Das Auto der Mutter.", en: "The mother’s car." },
      { de: "Das Auto des Mädchens.", en: "The girl’s car." },
      { de: "Das Auto der Eltern.", en: "The parents’ car." },
      { de: "Das Buch des Bruders ist interessant.", en: "The brother’s book is interesting.", note: "Genitiv + Nom" },
      { de: "Das Kind der Schwester ist schön.", en: "The sister’s child is beautiful.", note: "Genitiv + Nom" },
      { de: "Ich benutze einen Laptop des Mädchens.", en: "I use a girl’s laptop.", note: "Genitiv + Akk" },
      { de: "Sie isst die Schokolade der Kinder.", en: "She eats the children’s chocolate.", note: "Genitiv + Akk" },
      { de: "Wir kaufen den Kindern des Bruders die Schokolade.", en: "We buy the brother’s children the chocolate.", note: "Genitiv + Dat" },
      { de: "Die Oma erzählt dem Kind der Schwester die Geschichte.", en: "Grandma tells the sister’s child the story.", note: "Genitiv + Dat" },
    ],
  },
  {
    id: "genitiv-prep",
    title: "Genitiv-Präpositionen",
    titleEn: "Genitive prepositions",
    description: "anstatt · außerhalb · innerhalb · infolge · während · wegen · trotz · mithilfe",
    examples: [
      { de: "Anstatt des Autos hat er ein Fahrrad gekauft.", en: "Instead of the car, he bought a bicycle.", note: "anstatt" },
      { de: "Das Hotel liegt außerhalb des Dorfes.", en: "The hotel is outside the village.", note: "außerhalb" },
      { de: "Innerhalb des Gebäudes gibt es eine große Halle.", en: "Inside the building there is a large hall.", note: "innerhalb" },
      { de: "Infolge des Sturms gibt es viele Schäden.", en: "As a result of the storm there is a lot of damage.", note: "infolge" },
      { de: "Während des Urlaubs habe ich viele Fotos gemacht.", en: "During the holiday I took many photos.", note: "während" },
      { de: "Wegen der hohen Kosten haben sie das Projekt aufgegeben.", en: "Because of the high costs they abandoned the project.", note: "wegen" },
      { de: "Trotz des schlechten Wetters gehen wir spazieren.", en: "Despite the bad weather we go for a walk.", note: "trotz" },
      { de: "Mithilfe des Computers hat er die Aufgabe schnell erledigt.", en: "With the help of the computer he finished the task quickly.", note: "mithilfe" },
    ],
  },
  {
    id: "w-fragen-cases",
    title: "W-Fragen · Fälle",
    titleEn: "W-questions by case",
    description: "Wer/Was · Wen/Was · Wem · Wessen — plus Welch- forms.",
    tips: ["W-Wort + Verb + Nom + …"],
    tables: [
      {
        caption: "welch- forms",
        headers: ["", "Nom", "Akk", "Dat"],
        rows: [
          ["m", "welcher", "welchen", "welchem"],
          ["f", "welche", "welche", "welcher"],
          ["n", "welches", "welches", "welchem"],
          ["pl", "welche", "welche", "welchen"],
        ],
      },
    ],
    examples: [
      { de: "Was ist neu?", en: "What is new?", note: "Nominativ (thing)" },
      { de: "Wer joggt jeden Tag?", en: "Who jogs every day?", note: "Nominativ (person)" },
      { de: "Wen sehe ich?", en: "Whom do I see?", note: "Akkusativ (person)" },
      { de: "Was habe ich getrunken?", en: "What did I drink?", note: "Akkusativ (thing)" },
      { de: "Wem helfe ich?", en: "Whom am I helping?", note: "Dativ" },
      { de: "Wem kauft der Vater ein Fahrrad?", en: "For whom is the father buying a bike?", note: "Dativ" },
      { de: "Wessen Laptop ist neu?", en: "Whose laptop is new?", note: "Genitiv" },
      { de: "Wessen Handy ist das?", en: "Whose phone is that?", note: "Genitiv" },
      { de: "Welcher Hund bellt?", en: "Which dog is barking?", note: "welch- Nom" },
      { de: "Welchen Laptop hast du gekauft?", en: "Which laptop did you buy?", note: "welch- Akk" },
      { de: "Welchem Mann gibst du das Buch?", en: "To which man are you giving the book?", note: "welch- Dat" },
      { de: "Welcher Frau hilfst du?", en: "Which woman are you helping?", note: "welch- Dat" },
    ],
  },
  {
    id: "w-fragen-list",
    title: "W-Fragen · Liste",
    titleEn: "Common W-questions",
    description: "wann · wo · warum · wie · wohin · woher · wie viel · wie lange…",
    pairs: [
      { en: "When?", de: "Wann?" },
      { en: "Where?", de: "Wo?" },
      { en: "Why?", de: "Warum?" },
      { en: "How?", de: "Wie?" },
      { en: "Where to?", de: "Wohin?" },
      { en: "Where from?", de: "Woher?" },
      { en: "How much / How many?", de: "Wie viel? / Wie viele?" },
      { en: "How long?", de: "Wie lange?" },
      { en: "How often?", de: "Wie oft?" },
      { en: "With what?", de: "Womit?" },
      { en: "For what purpose?", de: "Wozu?" },
    ],
    examples: [
      { de: "Wann fährst du nach Berlin?", en: "When are you going to Berlin?" },
      { de: "Wo bist du?", en: "Where are you?" },
      { de: "Wo ist die Toilette?", en: "Where is the toilet?" },
      { de: "Warum lernst du Deutsch?", en: "Why are you learning German?" },
      { de: "Wie geht es dir?", en: "How are you?" },
      { de: "Wie gehst du zur Arbeit?", en: "How do you go to work?" },
      { de: "Wohin fahrt ihr in den Urlaub?", en: "Where are you going on holiday?" },
      { de: "Woher kommen Sie?", en: "Where do you come from?" },
      { de: "Wie viel kostet das Brot?", en: "How much does the bread cost?" },
      { de: "Wie viele Äpfel brauchst du?", en: "How many apples do you need?" },
      { de: "Wie lange dauert der Film?", en: "How long does the film last?" },
      { de: "Wie oft joggen Sie pro Woche?", en: "How often do you jog per week?" },
      { de: "Womit schreibst du?", en: "What are you writing with?" },
      { de: "Wozu brauchen die Kinder den Laptop?", en: "What do the children need the laptop for?" },
    ],
  },
  {
    id: "connectors",
    title: "Konnektoren",
    titleEn: "Connectors",
    description: "Coordinating (position 0) and main-clause connectors (verb after connector).",
    tips: [
      "Position 0: und · aber · oder · denn · sondern · doch — next clause keeps normal word order.",
      "Main-clause connectors (Deshalb, Trotzdem…): Connector + Verb + Nom + …",
    ],
    pairs: [
      { en: "and", de: "und" },
      { en: "but", de: "aber" },
      { en: "or", de: "oder" },
      { en: "because (coord.)", de: "denn" },
      { en: "but rather", de: "sondern" },
      { en: "but / yet", de: "doch" },
      { en: "That’s why", de: "Deshalb" },
      { en: "In spite of that", de: "Trotzdem" },
      { en: "Hence", de: "Daher" },
      { en: "Moreover", de: "Außerdem" },
      { en: "However", de: "Allerdings" },
      { en: "By the way", de: "Übrigens" },
      { en: "Then", de: "Dann" },
      { en: "Afterwards", de: "Danach" },
    ],
    examples: [
      { de: "Er ist fleißig, und sein Bruder ist faul.", en: "He is hardworking, and his brother is lazy.", note: "und" },
      { de: "Wir wollen gehen, aber es regnet.", en: "We want to go, but it is raining.", note: "aber" },
      { de: "Willst du bleiben oder gehen?", en: "Do you want to stay or go?", note: "oder" },
      { de: "Ich lerne Deutsch, denn ich möchte in Deutschland lernen.", en: "I learn German because I want to study in Germany.", note: "denn" },
      { de: "Ich trinke keinen Kaffee, sondern den Saft.", en: "I don’t drink coffee, but rather the juice.", note: "sondern" },
      { de: "Es regnet. Trotzdem gehen wir spazieren.", en: "It is raining. Still, we go for a walk.", note: "Trotzdem" },
      { de: "Ich bin krank. Deshalb bleibe ich zu Hause.", en: "I am sick. That’s why I stay at home.", note: "Deshalb" },
    ],
  },
];
