/** Shared quiz words for hourly notifications (app + service worker). */
const QUIZ_WORDS = [
  { de: "Hallo", en: "hello" },
  { de: "Danke", en: "thank you" },
  { de: "Bitte", en: "please / you're welcome" },
  { de: "Guten Morgen", en: "good morning" },
  { de: "die Familie", en: "family" },
  { de: "der Freund", en: "friend (m)" },
  { de: "das Wasser", en: "water" },
  { de: "der Kaffee", en: "coffee" },
  { de: "das Brot", en: "bread" },
  { de: "der Apfel", en: "apple" },
  { de: "das Haus", en: "house" },
  { de: "die Wohnung", en: "apartment" },
  { de: "der Schlüssel", en: "key" },
  { de: "die Stadt", en: "city" },
  { de: "der Zug", en: "train" },
  { de: "der Bus", en: "bus" },
  { de: "heute", en: "today" },
  { de: "morgen", en: "tomorrow" },
  { de: "gestern", en: "yesterday" },
  { de: "das Wetter", en: "weather" },
  { de: "die Sonne", en: "sun" },
  { de: "lernen", en: "to learn" },
  { de: "sprechen", en: "to speak" },
  { de: "verstehen", en: "to understand" },
  { de: "arbeiten", en: "to work" },
  { de: "schlafen", en: "to sleep" },
  { de: "essen", en: "to eat" },
  { de: "trinken", en: "to drink" },
  { de: "rot", en: "red" },
  { de: "blau", en: "blue" },
  { de: "grün", en: "green" },
  { de: "groß", en: "big / tall" },
  { de: "klein", en: "small" },
  { de: "gut", en: "good" },
  { de: "schlecht", en: "bad" },
  { de: "schnell", en: "fast" },
  { de: "langsam", en: "slow" },
  { de: "glücklich", en: "happy" },
  { de: "traurig", en: "sad" },
  { de: "müde", en: "tired" },
  { de: "der Hund", en: "dog" },
  { de: "die Katze", en: "cat" },
  { de: "der Baum", en: "tree" },
  { de: "die Blume", en: "flower" },
  { de: "der Berg", en: "mountain" },
  { de: "das Meer", en: "sea" },
  { de: "kaufen", en: "to buy" },
  { de: "teuer", en: "expensive" },
  { de: "billig", en: "cheap" },
  { de: "das Handy", en: "mobile phone" },
  { de: "die Schule", en: "school" },
  { de: "die Arbeit", en: "work / job" },
  { de: "Hilfe!", en: "Help!" },
  { de: "die Zeit", en: "time" },
  { de: "der Tag", en: "day" },
  { de: "die Nacht", en: "night" },
  { de: "links", en: "left" },
  { de: "rechts", en: "right" },
  { de: "ja", en: "yes" },
  { de: "nein", en: "no" },
  { de: "vielleicht", en: "maybe" },
  { de: "und", en: "and" },
  { de: "oder", en: "or" },
  { de: "aber", en: "but" },
  { de: "weil", en: "because" },
  { de: "ich", en: "I" },
  { de: "du", en: "you" },
  { de: "wir", en: "we" },
  { de: "sie", en: "she / they" },
  { de: "Freundlichkeit", en: "kindness" },
  { de: "die Reise", en: "trip / journey" },
  { de: "das Buch", en: "book" },
  { de: "lesen", en: "to read" },
  { de: "schreiben", en: "to write" },
  { de: "hören", en: "to hear" },
  { de: "sehen", en: "to see" },
  { de: "kommen", en: "to come" },
  { de: "gehen", en: "to go" },
  { de: "machen", en: "to do / make" },
  { de: "können", en: "can / to be able to" },
];

function pickQuizWord() {
  return QUIZ_WORDS[Math.floor(Math.random() * QUIZ_WORDS.length)];
}
