/** @typedef {{ de: string, en: string }} Word */
/** @typedef {{ words: Word[] }} StoryParagraph */
/**
 * @typedef {{
 *   id: string,
 *   title: string,
 *   titleEn: string,
 *   excerpt: string,
 *   readingMinutes: number,
 *   paragraphs: StoryParagraph[]
 * }} Story
 */

/** @type {Story[]} */
const STORIES = [
  {
    id: "story-schluessel",
    title: "Der verlorene Schlüssel",
    titleEn: "The Lost Key",
    excerpt: "Lena verliert ihren Wohnungsschlüssel und findet mehr als nur Metall.",
    readingMinutes: 4,
    paragraphs: [
      {
        words: [
          { de: "An", en: "on" },
          { de: "einem", en: "a" },
          { de: "kühlen", en: "cool" },
          { de: "Herbstmorgen", en: "autumn morning" },
          { de: "wachte", en: "woke" },
          { de: "Lena", en: "Lena" },
          { de: "früher", en: "earlier" },
          { de: "auf", en: "up" },
          { de: "als", en: "than" },
          { de: "sonst.", en: "usual." },
          { de: "Die", en: "the" },
          { de: "Sonne", en: "sun" },
          { de: "lag", en: "lay" },
          { de: "noch", en: "still" },
          { de: "hinter", en: "behind" },
          { de: "den", en: "the" },
          { de: "Dächern,", en: "roofs," },
          { de: "aber", en: "but" },
          { de: "sie", en: "she" },
          { de: "wollte", en: "wanted" },
          { de: "rechtzeitig", en: "on time" },
          { de: "zur", en: "to the" },
          { de: "Arbeit", en: "work" },
          { de: "kommen.", en: "to come." },
        ],
      },
      {
        words: [
          { de: "Als", en: "when" },
          { de: "sie", en: "she" },
          { de: "ihre", en: "her" },
          { de: "Tasche", en: "bag" },
          { de: "öffnete,", en: "opened," },
          { de: "fehlte", en: "was missing" },
          { de: "etwas", en: "something" },
          { de: "Wichtiges:", en: "important:" },
          { de: "der", en: "the" },
          { de: "Schlüssel", en: "key" },
          { de: "zur", en: "to the" },
          { de: "Wohnung.", en: "apartment." },
          { de: "Sie", en: "she" },
          { de: "suchte", en: "searched" },
          { de: "unter", en: "under" },
          { de: "den", en: "the" },
          { de: "Papieren,", en: "papers," },
          { de: "zwischen", en: "between" },
          { de: "den", en: "the" },
          { de: "Büchern", en: "books" },
          { de: "und", en: "and" },
          { de: "sogar", en: "even" },
          { de: "in", en: "in" },
          { de: "der", en: "the" },
          { de: "Küche.", en: "kitchen." },
          { de: "Nichts.", en: "nothing." },
        ],
      },
      {
        words: [
          { de: "Draußen", en: "outside" },
          { de: "begann", en: "began" },
          { de: "der", en: "the" },
          { de: "Tag", en: "day" },
          { de: "schon", en: "already" },
          { de: "lauter", en: "louder" },
          { de: "zu", en: "to" },
          { de: "werden.", en: "become." },
          { de: "Lena", en: "Lena" },
          { de: "lief", en: "ran" },
          { de: "die", en: "the" },
          { de: "Treppe", en: "stairs" },
          { de: "hinunter", en: "down" },
          { de: "und", en: "and" },
          { de: "fragte", en: "asked" },
          { de: "den", en: "the" },
          { de: "Hausmeister.", en: "building caretaker." },
          { de: "Er", en: "he" },
          { de: "schüttelte", en: "shook" },
          { de: "den", en: "the" },
          { de: "Kopf,", en: "head," },
          { de: "lächelte", en: "smiled" },
          { de: "aber", en: "but" },
          { de: "freundlich.", en: "kindly." },
        ],
      },
      {
        words: [
          { de: "„Vielleicht", en: "“maybe" },
          { de: "hast", en: "have" },
          { de: "du", en: "you" },
          { de: "ihn", en: "it" },
          { de: "gestern", en: "yesterday" },
          { de: "im", en: "in the" },
          { de: "Park", en: "park" },
          { de: "verloren“,", en: "lost,”" },
          { de: "sagte", en: "said" },
          { de: "er.", en: "he." },
          { de: "Lena", en: "Lena" },
          { de: "erinnerte", en: "remembered" },
          { de: "sich:", en: "herself:" },
          { de: "sie", en: "she" },
          { de: "hatte", en: "had" },
          { de: "dort", en: "there" },
          { de: "auf", en: "on" },
          { de: "einer", en: "a" },
          { de: "Bank", en: "bench" },
          { de: "gesessen", en: "sat" },
          { de: "und", en: "and" },
          { de: "ein", en: "a" },
          { de: "Buch", en: "book" },
          { de: "gelesen.", en: "read." },
        ],
      },
      {
        words: [
          { de: "Im", en: "in the" },
          { de: "Park", en: "park" },
          { de: "war", en: "was" },
          { de: "es", en: "it" },
          { de: "ruhig.", en: "quiet." },
          { de: "Blätter", en: "leaves" },
          { de: "tanzten", en: "danced" },
          { de: "über", en: "over" },
          { de: "den", en: "the" },
          { de: "Weg.", en: "path." },
          { de: "Neben", en: "beside" },
          { de: "der", en: "the" },
          { de: "Bank", en: "bench" },
          { de: "glänzte", en: "gleamed" },
          { de: "etwas", en: "something" },
          { de: "im", en: "in the" },
          { de: "Gras.", en: "grass." },
          { de: "Es", en: "it" },
          { de: "war", en: "was" },
          { de: "ihr", en: "her" },
          { de: "Schlüssel", en: "key" },
          { de: "—", en: "—" },
          { de: "und", en: "and" },
          { de: "daneben", en: "beside it" },
          { de: "lag", en: "lay" },
          { de: "eine", en: "a" },
          { de: "kleine", en: "small" },
          { de: "Notiz.", en: "note." },
        ],
      },
      {
        words: [
          { de: "Darauf", en: "on it" },
          { de: "stand:", en: "stood:" },
          { de: "„Ich", en: "“I" },
          { de: "habe", en: "have" },
          { de: "deinen", en: "your" },
          { de: "Schlüssel", en: "key" },
          { de: "gefunden", en: "found" },
          { de: "und", en: "and" },
          { de: "hier", en: "here" },
          { de: "gelassen.", en: "left." },
          { de: "Manchmal", en: "sometimes" },
          { de: "bringt", en: "brings" },
          { de: "ein", en: "a" },
          { de: "kleiner", en: "small" },
          { de: "Verlust", en: "loss" },
          { de: "uns", en: "us" },
          { de: "zurück", en: "back" },
          { de: "zu", en: "to" },
          { de: "dem,", en: "that," },
          { de: "was", en: "what" },
          { de: "wichtig", en: "important" },
          { de: "ist.“", en: "is.”" },
          { de: "Lena", en: "Lena" },
          { de: "lächelte,", en: "smiled," },
          { de: "steckte", en: "put" },
          { de: "den", en: "the" },
          { de: "Schlüssel", en: "key" },
          { de: "ein", en: "in" },
          { de: "und", en: "and" },
          { de: "ging", en: "went" },
          { de: "langsam", en: "slowly" },
          { de: "nach", en: "toward" },
          { de: "Hause.", en: "home." },
        ],
      },
    ],
  },
  {
    id: "story-bibliothek",
    title: "Die flüsternde Bibliothek",
    titleEn: "The Whispering Library",
    excerpt: "In einer alten Stadtbibliothek sprechen die Bücher leise zu denen, die zuhören.",
    readingMinutes: 5,
    paragraphs: [
      {
        words: [
          { de: "Mitten", en: "in the middle" },
          { de: "in", en: "in" },
          { de: "der", en: "the" },
          { de: "Altstadt", en: "old town" },
          { de: "stand", en: "stood" },
          { de: "eine", en: "a" },
          { de: "Bibliothek,", en: "library," },
          { de: "die", en: "that" },
          { de: "älter", en: "older" },
          { de: "war", en: "was" },
          { de: "als", en: "than" },
          { de: "viele", en: "many" },
          { de: "Häuser", en: "houses" },
          { de: "darumherum.", en: "around it." },
          { de: "Die", en: "the" },
          { de: "Fenster", en: "windows" },
          { de: "waren", en: "were" },
          { de: "hoch,", en: "tall," },
          { de: "das", en: "the" },
          { de: "Holz", en: "wood" },
          { de: "duftete", en: "smelled" },
          { de: "nach", en: "of" },
          { de: "Jahren,", en: "years," },
          { de: "und", en: "and" },
          { de: "die", en: "the" },
          { de: "Treppen", en: "stairs" },
          { de: "knarrten", en: "creaked" },
          { de: "leise.", en: "quietly." },
        ],
      },
      {
        words: [
          { de: "Jonas", en: "Jonas" },
          { de: "kam", en: "came" },
          { de: "jeden", en: "every" },
          { de: "Donnerstag", en: "Thursday" },
          { de: "nach", en: "after" },
          { de: "der", en: "the" },
          { de: "Schule.", en: "school." },
          { de: "Er", en: "he" },
          { de: "liebte", en: "loved" },
          { de: "nicht", en: "not" },
          { de: "nur", en: "only" },
          { de: "die", en: "the" },
          { de: "Bücher,", en: "books," },
          { de: "sondern", en: "but rather" },
          { de: "auch", en: "also" },
          { de: "die", en: "the" },
          { de: "Stille.", en: "silence." },
          { de: "An", en: "on" },
          { de: "diesem", en: "this" },
          { de: "Tag", en: "day" },
          { de: "jedoch", en: "however" },
          { de: "hörte", en: "heard" },
          { de: "er", en: "he" },
          { de: "etwas", en: "something" },
          { de: "Seltsames:", en: "strange:" },
          { de: "ein", en: "a" },
          { de: "leises", en: "soft" },
          { de: "Flüstern", en: "whispering" },
          { de: "zwischen", en: "between" },
          { de: "den", en: "the" },
          { de: "Regalen.", en: "shelves." },
        ],
      },
      {
        words: [
          { de: "Er", en: "he" },
          { de: "folgte", en: "followed" },
          { de: "dem", en: "the" },
          { de: "Ton", en: "sound" },
          { de: "bis", en: "until" },
          { de: "zur", en: "to the" },
          { de: "hintersten", en: "rearmost" },
          { de: "Ecke.", en: "corner." },
          { de: "Dort", en: "there" },
          { de: "lag", en: "lay" },
          { de: "ein", en: "a" },
          { de: "dünnes", en: "thin" },
          { de: "Buch", en: "book" },
          { de: "mit", en: "with" },
          { de: "goldenen", en: "golden" },
          { de: "Buchstaben.", en: "letters." },
          { de: "Als", en: "when" },
          { de: "Jonas", en: "Jonas" },
          { de: "es", en: "it" },
          { de: "öffnete,", en: "opened," },
          { de: "wurden", en: "became" },
          { de: "die", en: "the" },
          { de: "Wörter", en: "words" },
          { de: "heller,", en: "brighter," },
          { de: "als", en: "as if" },
          { de: "ob", en: "if" },
          { de: "sie", en: "they" },
          { de: "atmen", en: "breathe" },
          { de: "könnten.", en: "could." },
        ],
      },
      {
        words: [
          { de: "„Wer", en: "“who" },
          { de: "liest,", en: "reads," },
          { de: "reist“,", en: "travels,”" },
          { de: "flüsterte", en: "whispered" },
          { de: "eine", en: "a" },
          { de: "Stimme.", en: "voice." },
          { de: "Jonas", en: "Jonas" },
          { de: "sah", en: "saw" },
          { de: "niemanden,", en: "no one," },
          { de: "aber", en: "but" },
          { de: "er", en: "he" },
          { de: "fühlte", en: "felt" },
          { de: "sich", en: "himself" },
          { de: "plötzlich", en: "suddenly" },
          { de: "an", en: "on" },
          { de: "einem", en: "a" },
          { de: "Strand,", en: "beach," },
          { de: "dann", en: "then" },
          { de: "in", en: "in" },
          { de: "einem", en: "a" },
          { de: "Zug", en: "train" },
          { de: "durch", en: "through" },
          { de: "Berge,", en: "mountains," },
          { de: "dann", en: "then" },
          { de: "in", en: "in" },
          { de: "einer", en: "a" },
          { de: "fremden", en: "foreign" },
          { de: "Stadt.", en: "city." },
        ],
      },
      {
        words: [
          { de: "Als", en: "when" },
          { de: "er", en: "he" },
          { de: "das", en: "the" },
          { de: "Buch", en: "book" },
          { de: "schloss,", en: "closed," },
          { de: "war", en: "was" },
          { de: "er", en: "he" },
          { de: "wieder", en: "again" },
          { de: "in", en: "in" },
          { de: "der", en: "the" },
          { de: "Bibliothek.", en: "library." },
          { de: "Die", en: "the" },
          { de: "Bibliothekarin", en: "librarian" },
          { de: "nickte", en: "nodded" },
          { de: "ihm", en: "to him" },
          { de: "zu,", en: "toward," },
          { de: "als", en: "as if" },
          { de: "ob", en: "if" },
          { de: "sie", en: "she" },
          { de: "alles", en: "everything" },
          { de: "wüsste.", en: "knew." },
          { de: "„Manche", en: "“some" },
          { de: "Geschichten“,", en: "stories,”" },
          { de: "sagte", en: "said" },
          { de: "sie", en: "she" },
          { de: "leise,", en: "quietly," },
          { de: "„warten", en: "“wait" },
          { de: "nur", en: "only" },
          { de: "auf", en: "for" },
          { de: "den", en: "the" },
          { de: "richtigen", en: "right" },
          { de: "Leser.“", en: "reader.”" },
        ],
      },
      {
        words: [
          { de: "Jonas", en: "Jonas" },
          { de: "stellte", en: "placed" },
          { de: "das", en: "the" },
          { de: "Buch", en: "book" },
          { de: "zurück,", en: "back," },
          { de: "aber", en: "but" },
          { de: "er", en: "he" },
          { de: "nahm", en: "took" },
          { de: "die", en: "the" },
          { de: "Erinnerung", en: "memory" },
          { de: "mit.", en: "with." },
          { de: "Von", en: "from" },
          { de: "diesem", en: "this" },
          { de: "Tag", en: "day" },
          { de: "an", en: "on" },
          { de: "wusste", en: "knew" },
          { de: "er:", en: "he:" },
          { de: "Lesen", en: "reading" },
          { de: "ist", en: "is" },
          { de: "nicht", en: "not" },
          { de: "nur", en: "only" },
          { de: "Information.", en: "information." },
          { de: "Es", en: "it" },
          { de: "ist", en: "is" },
          { de: "eine", en: "a" },
          { de: "Tür,", en: "door," },
          { de: "die", en: "that" },
          { de: "sich", en: "itself" },
          { de: "öffnet,", en: "opens," },
          { de: "wenn", en: "when" },
          { de: "man", en: "one" },
          { de: "wirklich", en: "really" },
          { de: "zuhört.", en: "listens." },
        ],
      },
    ],
  },
  {
    id: "story-markt",
    title: "Ein Samstag auf dem Markt",
    titleEn: "A Saturday at the Market",
    excerpt: "Farah entdeckt auf dem Wochenmarkt Farben, Gerüche und ein neues Wortgefühl.",
    readingMinutes: 4,
    paragraphs: [
      {
        words: [
          { de: "Samstagmorgen", en: "Saturday morning" },
          { de: "bedeutete", en: "meant" },
          { de: "für", en: "for" },
          { de: "Farah", en: "Farah" },
          { de: "immer", en: "always" },
          { de: "dasselbe:", en: "the same:" },
          { de: "der", en: "the" },
          { de: "Markt", en: "market" },
          { de: "in", en: "in" },
          { de: "der", en: "the" },
          { de: "Stadtmitte.", en: "city center." },
          { de: "Stände", en: "stalls" },
          { de: "standen", en: "stood" },
          { de: "dicht", en: "densely" },
          { de: "nebeneinander,", en: "side by side," },
          { de: "und", en: "and" },
          { de: "die", en: "the" },
          { de: "Luft", en: "air" },
          { de: "roch", en: "smelled" },
          { de: "nach", en: "of" },
          { de: "Brot,", en: "bread," },
          { de: "Käse", en: "cheese" },
          { de: "und", en: "and" },
          { de: "frischen", en: "fresh" },
          { de: "Kräutern.", en: "herbs." },
        ],
      },
      {
        words: [
          { de: "Sie", en: "she" },
          { de: "kaufte", en: "bought" },
          { de: "Äpfel", en: "apples" },
          { de: "bei", en: "from" },
          { de: "einer", en: "a" },
          { de: "Frau", en: "woman" },
          { de: "mit", en: "with" },
          { de: "roten", en: "red" },
          { de: "Handschuhen.", en: "gloves." },
          { de: "„Welche", en: "“which" },
          { de: "sind", en: "are" },
          { de: "süß?“,", en: "sweet?”," },
          { de: "fragte", en: "asked" },
          { de: "Farah.", en: "Farah." },
          { de: "Die", en: "the" },
          { de: "Frau", en: "woman" },
          { de: "reichte", en: "handed" },
          { de: "ihr", en: "her" },
          { de: "einen", en: "an" },
          { de: "Apfel", en: "apple" },
          { de: "und", en: "and" },
          { de: "sagte:", en: "said:" },
          { de: "„Probier", en: "“try" },
          { de: "ihn.", en: "it." },
          { de: "Dann", en: "then" },
          { de: "weißt", en: "know" },
          { de: "du", en: "you" },
          { de: "es", en: "it" },
          { de: "selbst.“", en: "yourself.”" },
        ],
      },
      {
        words: [
          { de: "Weiter", en: "further" },
          { de: "vorn", en: "ahead" },
          { de: "spielte", en: "played" },
          { de: "ein", en: "a" },
          { de: "Musiker", en: "musician" },
          { de: "Geige.", en: "violin." },
          { de: "Kinder", en: "children" },
          { de: "tanzten,", en: "danced," },
          { de: "Hunde", en: "dogs" },
          { de: "warteten", en: "waited" },
          { de: "geduldig", en: "patiently" },
          { de: "neben", en: "beside" },
          { de: "Einkaufstaschen,", en: "shopping bags," },
          { de: "und", en: "and" },
          { de: "jemand", en: "someone" },
          { de: "lachte", en: "laughed" },
          { de: "so", en: "so" },
          { de: "laut,", en: "loudly," },
          { de: "dass", en: "that" },
          { de: "Farah", en: "Farah" },
          { de: "mitlachen", en: "laugh along" },
          { de: "musste.", en: "had to." },
          { de: "Der", en: "the" },
          { de: "Markt", en: "market" },
          { de: "fühlte", en: "felt" },
          { de: "sich", en: "itself" },
          { de: "an", en: "like" },
          { de: "wie", en: "like" },
          { de: "eine", en: "a" },
          { de: "kleine", en: "small" },
          { de: "Welt.", en: "world." },
        ],
      },
      {
        words: [
          { de: "Am", en: "at the" },
          { de: "Blumenstand", en: "flower stall" },
          { de: "lernte", en: "learned" },
          { de: "sie", en: "she" },
          { de: "ein", en: "a" },
          { de: "neues", en: "new" },
          { de: "Wort:", en: "word:" },
          { de: "„Strauß“.", en: "“bouquet”." },
          { de: "Sie", en: "she" },
          { de: "wiederholte", en: "repeated" },
          { de: "es", en: "it" },
          { de: "leise,", en: "quietly," },
          { de: "dann", en: "then" },
          { de: "lauter,", en: "louder," },
          { de: "bis", en: "until" },
          { de: "es", en: "it" },
          { de: "sich", en: "itself" },
          { de: "richtig", en: "right" },
          { de: "anfühlte.", en: "felt." },
          { de: "Der", en: "the" },
          { de: "Verkäufer", en: "seller" },
          { de: "nickte", en: "nodded" },
          { de: "zufrieden.", en: "contentedly." },
        ],
      },
      {
        words: [
          { de: "Als", en: "when" },
          { de: "Farah", en: "Farah" },
          { de: "nach", en: "toward" },
          { de: "Hause", en: "home" },
          { de: "ging,", en: "went," },
          { de: "trug", en: "carried" },
          { de: "sie", en: "she" },
          { de: "nicht", en: "not" },
          { de: "nur", en: "only" },
          { de: "Obst", en: "fruit" },
          { de: "und", en: "and" },
          { de: "Blumen.", en: "flowers." },
          { de: "Sie", en: "she" },
          { de: "trug", en: "carried" },
          { de: "auch", en: "also" },
          { de: "Sätze,", en: "sentences," },
          { de: "die", en: "that" },
          { de: "sie", en: "she" },
          { de: "gehört,", en: "heard," },
          { de: "gesagt", en: "said" },
          { de: "und", en: "and" },
          { de: "gefühlt", en: "felt" },
          { de: "hatte.", en: "had." },
          { de: "Und", en: "and" },
          { de: "genau", en: "exactly" },
          { de: "so,", en: "so," },
          { de: "dachte", en: "thought" },
          { de: "sie,", en: "she," },
          { de: "lernt", en: "learns" },
          { de: "man", en: "one" },
          { de: "eine", en: "a" },
          { de: "Sprache:", en: "language:" },
          { de: "Stück", en: "piece" },
          { de: "für", en: "for" },
          { de: "Stück,", en: "piece," },
          { de: "Samstag", en: "Saturday" },
          { de: "für", en: "for" },
          { de: "Samstag.", en: "Saturday." },
        ],
      },
    ],
  },
];
