/** @typedef {{ de: string, en: string, note?: string }} VocabWord */
/**
 * @typedef {{
 *   de: string,
 *   en: string,
 *   present: string,
 *   past: string,
 *   future: string,
 *   note?: string,
 *   related?: VocabWord[]
 * }} VocabVerb
 */
/**
 * @typedef {{
 *   id: string,
 *   title: string,
 *   titleEn: string,
 *   description: string,
 *   kind?: "words" | "verbs",
 *   words: Array<VocabWord | VocabVerb>
 * }} VocabSection
 */

/** @type {VocabSection[]} */
const VOCAB_SECTIONS = [
  {
    id: "verbs-tenses",
    title: "Verben & Zeiten",
    titleEn: "Verbs: Present, Past & Future",
    kind: "verbs",
    description:
      "Core verbs with ich-forms in present, past, and future. Tap any form to hear it. Related nouns keep der / die / das colors.",
    words: [
      {
        de: "lernen",
        en: "to learn",
        present: "ich lerne",
        past: "ich lernte / habe gelernt",
        future: "ich werde lernen",
        related: [{ de: "das Deutsch", en: "German", note: "neuter" }],
      },
      {
        de: "sprechen",
        en: "to speak",
        present: "ich spreche",
        past: "ich sprach / habe gesprochen",
        future: "ich werde sprechen",
        related: [{ de: "die Sprache", en: "language", note: "feminine" }],
      },
      {
        de: "gehen",
        en: "to go",
        present: "ich gehe",
        past: "ich ging / bin gegangen",
        future: "ich werde gehen",
        related: [{ de: "der Weg", en: "way / path", note: "masculine" }],
      },
      {
        de: "kommen",
        en: "to come",
        present: "ich komme",
        past: "ich kam / bin gekommen",
        future: "ich werde kommen",
        related: [{ de: "der Besuch", en: "visit", note: "masculine" }],
      },
      {
        de: "machen",
        en: "to do / make",
        present: "ich mache",
        past: "ich machte / habe gemacht",
        future: "ich werde machen",
        related: [{ de: "die Arbeit", en: "work", note: "feminine" }],
      },
      {
        de: "haben",
        en: "to have",
        present: "ich habe",
        past: "ich hatte / habe gehabt",
        future: "ich werde haben",
        related: [{ de: "die Zeit", en: "time", note: "feminine" }],
      },
      {
        de: "sein",
        en: "to be",
        present: "ich bin",
        past: "ich war / bin gewesen",
        future: "ich werde sein",
        related: [{ de: "der Mensch", en: "person", note: "masculine" }],
      },
      {
        de: "essen",
        en: "to eat",
        present: "ich esse",
        past: "ich aß / habe gegessen",
        future: "ich werde essen",
        related: [{ de: "das Essen", en: "food / meal", note: "neuter" }],
      },
      {
        de: "trinken",
        en: "to drink",
        present: "ich trinke",
        past: "ich trank / habe getrunken",
        future: "ich werde trinken",
        related: [{ de: "das Wasser", en: "water", note: "neuter" }],
      },
      {
        de: "lesen",
        en: "to read",
        present: "ich lese",
        past: "ich las / habe gelesen",
        future: "ich werde lesen",
        related: [{ de: "das Buch", en: "book", note: "neuter" }],
      },
      {
        de: "schreiben",
        en: "to write",
        present: "ich schreibe",
        past: "ich schrieb / habe geschrieben",
        future: "ich werde schreiben",
        related: [{ de: "der Brief", en: "letter", note: "masculine" }],
      },
      {
        de: "sehen",
        en: "to see",
        present: "ich sehe",
        past: "ich sah / habe gesehen",
        future: "ich werde sehen",
        related: [{ de: "das Bild", en: "picture", note: "neuter" }],
      },
      {
        de: "hören",
        en: "to hear / listen",
        present: "ich höre",
        past: "ich hörte / habe gehört",
        future: "ich werde hören",
        related: [{ de: "die Musik", en: "music", note: "feminine" }],
      },
      {
        de: "wohnen",
        en: "to live (reside)",
        present: "ich wohne",
        past: "ich wohnte / habe gewohnt",
        future: "ich werde wohnen",
        related: [{ de: "die Wohnung", en: "apartment", note: "feminine" }],
      },
      {
        de: "arbeiten",
        en: "to work",
        present: "ich arbeite",
        past: "ich arbeitete / habe gearbeitet",
        future: "ich werde arbeiten",
        related: [{ de: "der Job", en: "job", note: "masculine" }],
      },
      {
        de: "kaufen",
        en: "to buy",
        present: "ich kaufe",
        past: "ich kaufte / habe gekauft",
        future: "ich werde kaufen",
        related: [{ de: "der Markt", en: "market", note: "masculine" }],
      },
      {
        de: "kochen",
        en: "to cook",
        present: "ich koche",
        past: "ich kochte / habe gekocht",
        future: "ich werde kochen",
        related: [{ de: "die Küche", en: "kitchen", note: "feminine" }],
      },
      {
        de: "schlafen",
        en: "to sleep",
        present: "ich schlafe",
        past: "ich schlief / habe geschlafen",
        future: "ich werde schlafen",
        related: [{ de: "das Bett", en: "bed", note: "neuter" }],
      },
      {
        de: "fahren",
        en: "to drive / go (by vehicle)",
        present: "ich fahre",
        past: "ich fuhr / bin gefahren",
        future: "ich werde fahren",
        related: [{ de: "das Auto", en: "car", note: "neuter" }],
      },
      {
        de: "helfen",
        en: "to help",
        present: "ich helfe",
        past: "ich half / habe geholfen",
        future: "ich werde helfen",
        related: [{ de: "der Freund", en: "friend (m)", note: "masculine" }],
      },
      {
        de: "finden",
        en: "to find",
        present: "ich finde",
        past: "ich fand / habe gefunden",
        future: "ich werde finden",
        related: [{ de: "der Schlüssel", en: "key", note: "masculine" }],
      },
      {
        de: "verstehen",
        en: "to understand",
        present: "ich verstehe",
        past: "ich verstand / habe verstanden",
        future: "ich werde verstehen",
        related: [{ de: "die Frage", en: "question", note: "feminine" }],
      },
      {
        de: "denken",
        en: "to think",
        present: "ich denke",
        past: "ich dachte / habe gedacht",
        future: "ich werde denken",
        related: [{ de: "die Idee", en: "idea", note: "feminine" }],
      },
      {
        de: "spielen",
        en: "to play",
        present: "ich spiele",
        past: "ich spielte / habe gespielt",
        future: "ich werde spielen",
        related: [{ de: "das Spiel", en: "game", note: "neuter" }],
      },
      {
        de: "öffnen",
        en: "to open",
        present: "ich öffne",
        past: "ich öffnete / habe geöffnet",
        future: "ich werde öffnen",
        related: [{ de: "die Tür", en: "door", note: "feminine" }],
      },
      {
        de: "schließen",
        en: "to close",
        present: "ich schließe",
        past: "ich schloss / habe geschlossen",
        future: "ich werde schließen",
        related: [{ de: "das Fenster", en: "window", note: "neuter" }],
      },
      {
        de: "anfangen",
        en: "to begin",
        present: "ich fange an",
        past: "ich fing an / habe angefangen",
        future: "ich werde anfangen",
        related: [{ de: "der Anfang", en: "beginning", note: "masculine" }],
      },
      {
        de: "aufhören",
        en: "to stop",
        present: "ich höre auf",
        past: "ich hörte auf / habe aufgehört",
        future: "ich werde aufhören",
        related: [{ de: "das Ende", en: "end", note: "neuter" }],
      },
    ],
  },
  {
    id: "greetings",
    title: "Begrüßungen",
    titleEn: "Greetings & Politeness",
    description: "Everyday hellos, goodbyes, and polite phrases.",
    words: [
      { de: "Hallo", en: "hello" },
      { de: "Guten Morgen", en: "good morning" },
      { de: "Guten Tag", en: "good day" },
      { de: "Guten Abend", en: "good evening" },
      { de: "Gute Nacht", en: "good night" },
      { de: "Tschüss", en: "bye" },
      { de: "Auf Wiedersehen", en: "goodbye" },
      { de: "Bitte", en: "please / you're welcome" },
      { de: "Danke", en: "thank you" },
      { de: "Vielen Dank", en: "thank you very much" },
      { de: "Entschuldigung", en: "excuse me / sorry" },
      { de: "Ja", en: "yes" },
      { de: "Nein", en: "no" },
      { de: "Vielleicht", en: "maybe" },
      { de: "Wie geht's?", en: "how are you?" },
    ],
  },
  {
    id: "people",
    title: "Menschen & Familie",
    titleEn: "People & Family",
    description: "Words for people you meet and family members.",
    words: [
      { de: "der Mann", en: "man", note: "masculine" },
      { de: "die Frau", en: "woman", note: "feminine" },
      { de: "das Kind", en: "child", note: "neuter" },
      { de: "der Vater", en: "father", note: "masculine" },
      { de: "die Mutter", en: "mother", note: "feminine" },
      { de: "der Bruder", en: "brother", note: "masculine" },
      { de: "die Schwester", en: "sister", note: "feminine" },
      { de: "die Familie", en: "family", note: "feminine" },
      { de: "der Freund", en: "friend (m)", note: "masculine" },
      { de: "die Freundin", en: "friend (f)", note: "feminine" },
      { de: "der Lehrer", en: "teacher (m)", note: "masculine" },
      { de: "die Lehrerin", en: "teacher (f)", note: "feminine" },
      { de: "die Leute", en: "people", note: "plural" },
      { de: "der Name", en: "name", note: "masculine" },
    ],
  },
  {
    id: "food",
    title: "Essen & Trinken",
    titleEn: "Food & Drink",
    description: "Useful words for meals, markets, and cafés.",
    words: [
      { de: "das Wasser", en: "water", note: "neuter" },
      { de: "der Kaffee", en: "coffee", note: "masculine" },
      { de: "der Tee", en: "tea", note: "masculine" },
      { de: "das Brot", en: "bread", note: "neuter" },
      { de: "der Käse", en: "cheese", note: "masculine" },
      { de: "der Apfel", en: "apple", note: "masculine" },
      { de: "die Banane", en: "banana", note: "feminine" },
      { de: "das Fleisch", en: "meat", note: "neuter" },
      { de: "der Fisch", en: "fish", note: "masculine" },
      { de: "das Gemüse", en: "vegetables", note: "neuter" },
      { de: "die Suppe", en: "soup", note: "feminine" },
      { de: "das Frühstück", en: "breakfast", note: "neuter" },
      { de: "das Mittagessen", en: "lunch", note: "neuter" },
      { de: "das Abendessen", en: "dinner", note: "neuter" },
      { de: "lecker", en: "delicious" },
      { de: "hungrig", en: "hungry" },
      { de: "durstig", en: "thirsty" },
    ],
  },
  {
    id: "home",
    title: "Zuhause",
    titleEn: "Home & Daily Life",
    description: "Rooms, objects, and everyday home words.",
    words: [
      { de: "das Haus", en: "house", note: "neuter" },
      { de: "die Wohnung", en: "apartment", note: "feminine" },
      { de: "die Tür", en: "door", note: "feminine" },
      { de: "das Fenster", en: "window", note: "neuter" },
      { de: "der Tisch", en: "table", note: "masculine" },
      { de: "der Stuhl", en: "chair", note: "masculine" },
      { de: "das Bett", en: "bed", note: "neuter" },
      { de: "die Küche", en: "kitchen", note: "feminine" },
      { de: "das Bad", en: "bathroom", note: "neuter" },
      { de: "das Zimmer", en: "room", note: "neuter" },
      { de: "der Schlüssel", en: "key", note: "masculine" },
      { de: "das Licht", en: "light", note: "neuter" },
      { de: "aufräumen", en: "to tidy up" },
      { de: "kochen", en: "to cook" },
      { de: "waschen", en: "to wash" },
    ],
  },
  {
    id: "travel",
    title: "Reisen & Stadt",
    titleEn: "Travel & City",
    description: "Getting around town and on trips.",
    words: [
      { de: "die Stadt", en: "city", note: "feminine" },
      { de: "der Bahnhof", en: "train station", note: "masculine" },
      { de: "der Zug", en: "train", note: "masculine" },
      { de: "der Bus", en: "bus", note: "masculine" },
      { de: "die Straße", en: "street", note: "feminine" },
      { de: "der Weg", en: "way / path", note: "masculine" },
      { de: "die Karte", en: "map / ticket", note: "feminine" },
      { de: "das Hotel", en: "hotel", note: "neuter" },
      { de: "der Flughafen", en: "airport", note: "masculine" },
      { de: "links", en: "left" },
      { de: "rechts", en: "right" },
      { de: "geradeaus", en: "straight ahead" },
      { de: "weit", en: "far" },
      { de: "nah", en: "near" },
      { de: "Wo ist…?", en: "Where is…?" },
      { de: "Ich suche…", en: "I am looking for…" },
    ],
  },
  {
    id: "time",
    title: "Zeit & Wetter",
    titleEn: "Time & Weather",
    description: "Days, time phrases, and talking about the weather.",
    words: [
      { de: "heute", en: "today" },
      { de: "morgen", en: "tomorrow" },
      { de: "gestern", en: "yesterday" },
      { de: "jetzt", en: "now" },
      { de: "später", en: "later" },
      { de: "die Woche", en: "week", note: "feminine" },
      { de: "der Monat", en: "month", note: "masculine" },
      { de: "das Jahr", en: "year", note: "neuter" },
      { de: "die Uhr", en: "clock / o'clock", note: "feminine" },
      { de: "das Wetter", en: "weather", note: "neuter" },
      { de: "die Sonne", en: "sun", note: "feminine" },
      { de: "der Regen", en: "rain", note: "masculine" },
      { de: "der Wind", en: "wind", note: "masculine" },
      { de: "kalt", en: "cold" },
      { de: "warm", en: "warm" },
      { de: "schön", en: "nice / beautiful" },
    ],
  },
  {
    id: "verbs",
    title: "Wichtige Verben",
    titleEn: "Essential Verbs",
    description: "High-frequency verbs for daily conversation.",
    words: [
      { de: "sein", en: "to be" },
      { de: "haben", en: "to have" },
      { de: "machen", en: "to do / make" },
      { de: "gehen", en: "to go" },
      { de: "kommen", en: "to come" },
      { de: "sehen", en: "to see" },
      { de: "hören", en: "to hear" },
      { de: "sprechen", en: "to speak" },
      { de: "verstehen", en: "to understand" },
      { de: "lernen", en: "to learn" },
      { de: "lesen", en: "to read" },
      { de: "schreiben", en: "to write" },
      { de: "essen", en: "to eat" },
      { de: "trinken", en: "to drink" },
      { de: "schlafen", en: "to sleep" },
      { de: "arbeiten", en: "to work" },
      { de: "wohnen", en: "to live (reside)" },
      { de: "können", en: "can / to be able to" },
      { de: "müssen", en: "must / to have to" },
      { de: "wollen", en: "to want" },
    ],
  },
  {
    id: "colors-numbers",
    title: "Farben & Zahlen",
    titleEn: "Colors & Numbers",
    description: "Basic colors and numbers for shopping and counting.",
    words: [
      { de: "rot", en: "red" },
      { de: "blau", en: "blue" },
      { de: "grün", en: "green" },
      { de: "gelb", en: "yellow" },
      { de: "schwarz", en: "black" },
      { de: "weiß", en: "white" },
      { de: "eins", en: "one" },
      { de: "zwei", en: "two" },
      { de: "drei", en: "three" },
      { de: "vier", en: "four" },
      { de: "fünf", en: "five" },
      { de: "zehn", en: "ten" },
      { de: "zwanzig", en: "twenty" },
      { de: "hundert", en: "hundred" },
      { de: "viel", en: "much / many" },
      { de: "wenig", en: "few / little" },
    ],
  },
  {
    id: "body-health",
    title: "Körper & Gesundheit",
    titleEn: "Body & Health",
    description: "Parts of the body and useful health phrases.",
    words: [
      { de: "der Kopf", en: "head", note: "masculine" },
      { de: "das Auge", en: "eye", note: "neuter" },
      { de: "das Ohr", en: "ear", note: "neuter" },
      { de: "die Nase", en: "nose", note: "feminine" },
      { de: "der Mund", en: "mouth", note: "masculine" },
      { de: "die Hand", en: "hand", note: "feminine" },
      { de: "der Fuß", en: "foot", note: "masculine" },
      { de: "der Rücken", en: "back", note: "masculine" },
      { de: "der Magen", en: "stomach", note: "masculine" },
      { de: "krank", en: "sick" },
      { de: "gesund", en: "healthy" },
      { de: "der Schmerz", en: "pain", note: "masculine" },
      { de: "der Arzt", en: "doctor (m)", note: "masculine" },
      { de: "die Ärztin", en: "doctor (f)", note: "feminine" },
      { de: "die Apotheke", en: "pharmacy", note: "feminine" },
      { de: "die Medizin", en: "medicine", note: "feminine" },
      { de: "Mir ist schlecht.", en: "I feel sick." },
      { de: "Ich habe Kopfschmerzen.", en: "I have a headache." },
    ],
  },
  {
    id: "clothing",
    title: "Kleidung",
    titleEn: "Clothing",
    description: "What to wear — shopping and daily outfits.",
    words: [
      { de: "das Hemd", en: "shirt", note: "neuter" },
      { de: "die Hose", en: "pants / trousers", note: "feminine" },
      { de: "der Rock", en: "skirt", note: "masculine" },
      { de: "das Kleid", en: "dress", note: "neuter" },
      { de: "die Jacke", en: "jacket", note: "feminine" },
      { de: "der Mantel", en: "coat", note: "masculine" },
      { de: "die Schuhe", en: "shoes", note: "plural" },
      { de: "die Socken", en: "socks", note: "plural" },
      { de: "der Hut", en: "hat", note: "masculine" },
      { de: "die Mütze", en: "cap / beanie", note: "feminine" },
      { de: "der Schal", en: "scarf", note: "masculine" },
      { de: "die Brille", en: "glasses", note: "feminine" },
      { de: "die Tasche", en: "bag", note: "feminine" },
      { de: "tragen", en: "to wear / carry" },
      { de: "anziehen", en: "to put on" },
      { de: "ausziehen", en: "to take off" },
      { de: "groß", en: "big / large (size)" },
      { de: "klein", en: "small" },
    ],
  },
  {
    id: "emotions",
    title: "Gefühle",
    titleEn: "Feelings & Emotions",
    description: "Say how you feel and describe moods.",
    words: [
      { de: "glücklich", en: "happy" },
      { de: "traurig", en: "sad" },
      { de: "müde", en: "tired" },
      { de: "wütend", en: "angry" },
      { de: "nervös", en: "nervous" },
      { de: "ruhig", en: "calm" },
      { de: "überrascht", en: "surprised" },
      { de: "verwirrt", en: "confused" },
      { de: "ängstlich", en: "afraid" },
      { de: "stolz", en: "proud" },
      { de: "einsam", en: "lonely" },
      { de: "zufrieden", en: "content / satisfied" },
      { de: "die Freude", en: "joy", note: "feminine" },
      { de: "die Angst", en: "fear", note: "feminine" },
      { de: "die Liebe", en: "love", note: "feminine" },
      { de: "Ich fühle mich…", en: "I feel…" },
      { de: "Mir geht es gut.", en: "I am doing well." },
      { de: "Mir geht es nicht gut.", en: "I am not doing well." },
    ],
  },
  {
    id: "animals",
    title: "Tiere",
    titleEn: "Animals",
    description: "Common pets and animals you might talk about.",
    words: [
      { de: "der Hund", en: "dog", note: "masculine" },
      { de: "die Katze", en: "cat", note: "feminine" },
      { de: "der Vogel", en: "bird", note: "masculine" },
      { de: "der Fisch", en: "fish", note: "masculine" },
      { de: "das Pferd", en: "horse", note: "neuter" },
      { de: "die Kuh", en: "cow", note: "feminine" },
      { de: "das Schwein", en: "pig", note: "neuter" },
      { de: "das Huhn", en: "chicken", note: "neuter" },
      { de: "der Hase", en: "rabbit / hare", note: "masculine" },
      { de: "die Maus", en: "mouse", note: "feminine" },
      { de: "der Bär", en: "bear", note: "masculine" },
      { de: "der Löwe", en: "lion", note: "masculine" },
      { de: "der Elefant", en: "elephant", note: "masculine" },
      { de: "das Tier", en: "animal", note: "neuter" },
      { de: "das Haustier", en: "pet", note: "neuter" },
      { de: "wild", en: "wild" },
    ],
  },
  {
    id: "nature",
    title: "Natur",
    titleEn: "Nature & Outdoors",
    description: "Landscape words for walks, travel, and seasons.",
    words: [
      { de: "der Baum", en: "tree", note: "masculine" },
      { de: "die Blume", en: "flower", note: "feminine" },
      { de: "der Wald", en: "forest", note: "masculine" },
      { de: "der Berg", en: "mountain", note: "masculine" },
      { de: "der See", en: "lake", note: "masculine" },
      { de: "das Meer", en: "sea", note: "neuter" },
      { de: "der Fluss", en: "river", note: "masculine" },
      { de: "der Strand", en: "beach", note: "masculine" },
      { de: "der Himmel", en: "sky", note: "masculine" },
      { de: "die Wolke", en: "cloud", note: "feminine" },
      { de: "der Schnee", en: "snow", note: "masculine" },
      { de: "der Frühling", en: "spring", note: "masculine" },
      { de: "der Sommer", en: "summer", note: "masculine" },
      { de: "der Herbst", en: "autumn", note: "masculine" },
      { de: "der Winter", en: "winter", note: "masculine" },
      { de: "die Natur", en: "nature", note: "feminine" },
    ],
  },
  {
    id: "shopping",
    title: "Einkaufen",
    titleEn: "Shopping",
    description: "Stores, money, and useful shopping phrases.",
    words: [
      { de: "der Laden", en: "shop", note: "masculine" },
      { de: "der Supermarkt", en: "supermarket", note: "masculine" },
      { de: "der Preis", en: "price", note: "masculine" },
      { de: "das Geld", en: "money", note: "neuter" },
      { de: "der Euro", en: "euro", note: "masculine" },
      { de: "teuer", en: "expensive" },
      { de: "billig", en: "cheap" },
      { de: "kostenlos", en: "free of charge" },
      { de: "kaufen", en: "to buy" },
      { de: "verkaufen", en: "to sell" },
      { de: "bezahlen", en: "to pay" },
      { de: "die Rechnung", en: "bill / invoice", note: "feminine" },
      { de: "die Quittung", en: "receipt", note: "feminine" },
      { de: "die Kasse", en: "checkout / cash register", note: "feminine" },
      { de: "Wie viel kostet das?", en: "How much does that cost?" },
      { de: "Ich möchte das kaufen.", en: "I would like to buy that." },
      { de: "Haben Sie…?", en: "Do you have…?" },
      { de: "Nur schauen.", en: "Just looking." },
    ],
  },
  {
    id: "restaurant",
    title: "Im Restaurant",
    titleEn: "At the Restaurant",
    description: "Ordering food and dining out with confidence.",
    words: [
      { de: "das Restaurant", en: "restaurant", note: "neuter" },
      { de: "die Speisekarte", en: "menu", note: "feminine" },
      { de: "der Kellner", en: "waiter", note: "masculine" },
      { de: "die Kellnerin", en: "waitress", note: "feminine" },
      { de: "der Tisch", en: "table", note: "masculine" },
      { de: "bestellen", en: "to order" },
      { de: "die Vorspeise", en: "starter / appetizer", note: "feminine" },
      { de: "die Hauptspeise", en: "main course", note: "feminine" },
      { de: "der Nachtisch", en: "dessert", note: "masculine" },
      { de: "das Getränk", en: "drink", note: "neuter" },
      { de: "das Glas", en: "glass", note: "neuter" },
      { de: "der Teller", en: "plate", note: "masculine" },
      { de: "das Messer", en: "knife", note: "neuter" },
      { de: "die Gabel", en: "fork", note: "feminine" },
      { de: "der Löffel", en: "spoon", note: "masculine" },
      { de: "Ich hätte gerne…", en: "I would like…" },
      { de: "Die Rechnung, bitte.", en: "The bill, please." },
      { de: "Stimmt so.", en: "Keep the change." },
    ],
  },
  {
    id: "school-work",
    title: "Schule & Arbeit",
    titleEn: "School & Work",
    description: "Classroom and workplace vocabulary.",
    words: [
      { de: "die Schule", en: "school", note: "feminine" },
      { de: "die Universität", en: "university", note: "feminine" },
      { de: "der Unterricht", en: "lesson / class", note: "masculine" },
      { de: "die Hausaufgabe", en: "homework", note: "feminine" },
      { de: "die Prüfung", en: "exam", note: "feminine" },
      { de: "das Büro", en: "office", note: "neuter" },
      { de: "die Arbeit", en: "work / job", note: "feminine" },
      { de: "der Kollege", en: "colleague (m)", note: "masculine" },
      { de: "die Kollegin", en: "colleague (f)", note: "feminine" },
      { de: "die Pause", en: "break", note: "feminine" },
      { de: "die Besprechung", en: "meeting", note: "feminine" },
      { de: "der Computer", en: "computer", note: "masculine" },
      { de: "die E-Mail", en: "email", note: "feminine" },
      { de: "studieren", en: "to study (at university)" },
      { de: "üben", en: "to practice" },
      { de: "erklären", en: "to explain" },
      { de: "Ich arbeite als…", en: "I work as…" },
    ],
  },
  {
    id: "technology",
    title: "Technik",
    titleEn: "Technology",
    description: "Phones, internet, and modern daily tech.",
    words: [
      { de: "das Handy", en: "mobile phone", note: "neuter" },
      { de: "das Telefon", en: "telephone", note: "neuter" },
      { de: "das Internet", en: "internet", note: "neuter" },
      { de: "die Website", en: "website", note: "feminine" },
      { de: "das Passwort", en: "password", note: "neuter" },
      { de: "laden", en: "to load / charge" },
      { de: "herunterladen", en: "to download" },
      { de: "hochladen", en: "to upload" },
      { de: "schalten", en: "to switch" },
      { de: "anmachen", en: "to turn on" },
      { de: "ausmachen", en: "to turn off" },
      { de: "die Nachricht", en: "message", note: "feminine" },
      { de: "die App", en: "app", note: "feminine" },
      { de: "WLAN", en: "Wi-Fi" },
      { de: "online", en: "online" },
      { de: "offline", en: "offline" },
      { de: "funktioniert nicht", en: "doesn't work" },
    ],
  },
  {
    id: "hobbies",
    title: "Hobbys & Sport",
    titleEn: "Hobbies & Sports",
    description: "Free-time activities and popular sports.",
    words: [
      { de: "das Hobby", en: "hobby", note: "neuter" },
      { de: "der Sport", en: "sport", note: "masculine" },
      { de: "Fußball spielen", en: "to play soccer" },
      { de: "schwimmen", en: "to swim" },
      { de: "laufen", en: "to run" },
      { de: "wandern", en: "to hike" },
      { de: "Rad fahren", en: "to bike / cycle" },
      { de: "Musik hören", en: "to listen to music" },
      { de: "tanzen", en: "to dance" },
      { de: "malen", en: "to paint" },
      { de: "fotografieren", en: "to take photos" },
      { de: "reisen", en: "to travel" },
      { de: "das Kino", en: "cinema", note: "neuter" },
      { de: "das Konzert", en: "concert", note: "neuter" },
      { de: "das Spiel", en: "game", note: "neuter" },
      { de: "Spaß haben", en: "to have fun" },
      { de: "Was machst du gerne?", en: "What do you like to do?" },
    ],
  },
  {
    id: "adjectives",
    title: "Nützliche Adjektive",
    titleEn: "Useful Adjectives",
    description: "Describing people, things, and situations.",
    words: [
      { de: "gut", en: "good" },
      { de: "schlecht", en: "bad" },
      { de: "neu", en: "new" },
      { de: "alt", en: "old" },
      { de: "jung", en: "young" },
      { de: "schnell", en: "fast" },
      { de: "langsam", en: "slow" },
      { de: "leicht", en: "easy / light" },
      { de: "schwer", en: "difficult / heavy" },
      { de: "wichtig", en: "important" },
      { de: "interessant", en: "interesting" },
      { de: "langweilig", en: "boring" },
      { de: "freundlich", en: "friendly" },
      { de: "höflich", en: "polite" },
      { de: "sauber", en: "clean" },
      { de: "schmutzig", en: "dirty" },
      { de: "offen", en: "open" },
      { de: "geschlossen", en: "closed" },
      { de: "richtig", en: "correct / right" },
      { de: "falsch", en: "wrong" },
    ],
  },
  {
    id: "connectors",
    title: "Verbindungswörter",
    titleEn: "Connecting Words",
    description: "Small words that make longer, clearer sentences.",
    words: [
      { de: "und", en: "and" },
      { de: "oder", en: "or" },
      { de: "aber", en: "but" },
      { de: "denn", en: "because / for" },
      { de: "weil", en: "because" },
      { de: "wenn", en: "if / when" },
      { de: "dann", en: "then" },
      { de: "also", en: "so / therefore" },
      { de: "deshalb", en: "therefore" },
      { de: "trotzdem", en: "nevertheless" },
      { de: "auch", en: "also" },
      { de: "noch", en: "still / yet" },
      { de: "schon", en: "already" },
      { de: "nur", en: "only" },
      { de: "sehr", en: "very" },
      { de: "zu", en: "too (excessively)" },
      { de: "mit", en: "with" },
      { de: "ohne", en: "without" },
      { de: "für", en: "for" },
      { de: "gegen", en: "against" },
    ],
  },
  {
    id: "emergency",
    title: "Notfall & Hilfe",
    titleEn: "Emergency & Help",
    description: "Important words when you need assistance fast.",
    words: [
      { de: "Hilfe!", en: "Help!" },
      { de: "Vorsicht!", en: "Watch out! / Caution!" },
      { de: "der Notfall", en: "emergency", note: "masculine" },
      { de: "die Polizei", en: "police", note: "feminine" },
      { de: "die Feuerwehr", en: "fire department", note: "feminine" },
      { de: "der Krankenwagen", en: "ambulance", note: "masculine" },
      { de: "das Krankenhaus", en: "hospital", note: "neuter" },
      { de: "verloren", en: "lost" },
      { de: "gefunden", en: "found" },
      { de: "gestohlen", en: "stolen" },
      { de: "der Unfall", en: "accident", note: "masculine" },
      { de: "die Adresse", en: "address", note: "feminine" },
      { de: "die Telefonnummer", en: "phone number", note: "feminine" },
      { de: "Rufen Sie bitte…", en: "Please call…" },
      { de: "Ich brauche Hilfe.", en: "I need help." },
      { de: "Wo ist die Toilette?", en: "Where is the toilet?" },
      { de: "Sprechen Sie Englisch?", en: "Do you speak English?" },
      { de: "Ich verstehe nicht.", en: "I don't understand." },
    ],
  },
  {
    id: "directions-places",
    title: "Orte in der Stadt",
    titleEn: "Places in Town",
    description: "Buildings and places you'll look for while out.",
    words: [
      { de: "die Bank", en: "bank / bench", note: "feminine" },
      { de: "die Post", en: "post office", note: "feminine" },
      { de: "das Museum", en: "museum", note: "neuter" },
      { de: "die Bibliothek", en: "library", note: "feminine" },
      { de: "der Park", en: "park", note: "masculine" },
      { de: "die Kirche", en: "church", note: "feminine" },
      { de: "das Rathaus", en: "city hall", note: "neuter" },
      { de: "die Schule", en: "school", note: "feminine" },
      { de: "das Krankenhaus", en: "hospital", note: "neuter" },
      { de: "die Apotheke", en: "pharmacy", note: "feminine" },
      { de: "der Markt", en: "market", note: "masculine" },
      { de: "das Café", en: "café", note: "neuter" },
      { de: "die Bäckerei", en: "bakery", note: "feminine" },
      { de: "der Platz", en: "square / place", note: "masculine" },
      { de: "die Brücke", en: "bridge", note: "feminine" },
      { de: "neben", en: "next to" },
      { de: "gegenüber", en: "opposite / across from" },
      { de: "zwischen", en: "between" },
    ],
  },
  {
    id: "daily-routines",
    title: "Tagesablauf",
    titleEn: "Daily Routines",
    description: "From morning to night — verbs for your day.",
    words: [
      { de: "aufstehen", en: "to get up" },
      { de: "sich waschen", en: "to wash oneself" },
      { de: "sich anziehen", en: "to get dressed" },
      { de: "frühstücken", en: "to have breakfast" },
      { de: "zur Arbeit gehen", en: "to go to work" },
      { de: "einkaufen gehen", en: "to go shopping" },
      { de: "nach Hause kommen", en: "to come home" },
      { de: "fernsehen", en: "to watch TV" },
      { de: "sich ausruhen", en: "to rest" },
      { de: "zu Bett gehen", en: "to go to bed" },
      { de: "einschlafen", en: "to fall asleep" },
      { de: "der Morgen", en: "morning", note: "masculine" },
      { de: "der Nachmittag", en: "afternoon", note: "masculine" },
      { de: "der Abend", en: "evening", note: "masculine" },
      { de: "die Nacht", en: "night", note: "feminine" },
      { de: "jeden Tag", en: "every day" },
      { de: "manchmal", en: "sometimes" },
      { de: "oft", en: "often" },
      { de: "selten", en: "rarely" },
      { de: "nie", en: "never" },
    ],
  },
];
