/** @typedef {{ de: string, en: string, note?: string }} VocabWord */
/**
 * @typedef {{
 *   id: string,
 *   title: string,
 *   titleEn: string,
 *   description: string,
 *   words: VocabWord[]
 * }} VocabSection
 */

/** @type {VocabSection[]} */
const VOCAB_SECTIONS = [
  {
    id: "greetings",
    title: "Begrüßungen",
    titleEn: "Greetings & Politeness",
    description: "Everyday hellos, goodbyes, and polite phrases.",
    words: [
      { de: "Hallo", en: "hello" },
      { de: "Guten Morgen", en: "good morning" },
      { de: "Guten Tag", en: "good day" },
      { de: "Guten Abend", en: "good evening" },
      { de: "Gute Nacht", en: "good night" },
      { de: "Tschüss", en: "bye" },
      { de: "Auf Wiedersehen", en: "goodbye" },
      { de: "Bitte", en: "please / you're welcome" },
      { de: "Danke", en: "thank you" },
      { de: "Vielen Dank", en: "thank you very much" },
      { de: "Entschuldigung", en: "excuse me / sorry" },
      { de: "Ja", en: "yes" },
      { de: "Nein", en: "no" },
      { de: "Vielleicht", en: "maybe" },
      { de: "Wie geht's?", en: "how are you?" },
    ],
  },
  {
    id: "people",
    title: "Menschen & Familie",
    titleEn: "People & Family",
    description: "Words for people you meet and family members.",
    words: [
      { de: "der Mann", en: "man", note: "masculine" },
      { de: "die Frau", en: "woman", note: "feminine" },
      { de: "das Kind", en: "child", note: "neuter" },
      { de: "der Vater", en: "father", note: "masculine" },
      { de: "die Mutter", en: "mother", note: "feminine" },
      { de: "der Bruder", en: "brother", note: "masculine" },
      { de: "die Schwester", en: "sister", note: "feminine" },
      { de: "die Familie", en: "family", note: "feminine" },
      { de: "der Freund", en: "friend (m)", note: "masculine" },
      { de: "die Freundin", en: "friend (f)", note: "feminine" },
      { de: "der Lehrer", en: "teacher (m)", note: "masculine" },
      { de: "die Lehrerin", en: "teacher (f)", note: "feminine" },
      { de: "die Leute", en: "people", note: "plural" },
      { de: "der Name", en: "name", note: "masculine" },
    ],
  },
  {
    id: "food",
    title: "Essen & Trinken",
    titleEn: "Food & Drink",
    description: "Useful words for meals, markets, and cafés.",
    words: [
      { de: "das Wasser", en: "water", note: "neuter" },
      { de: "der Kaffee", en: "coffee", note: "masculine" },
      { de: "der Tee", en: "tea", note: "masculine" },
      { de: "das Brot", en: "bread", note: "neuter" },
      { de: "der Käse", en: "cheese", note: "masculine" },
      { de: "der Apfel", en: "apple", note: "masculine" },
      { de: "die Banane", en: "banana", note: "feminine" },
      { de: "das Fleisch", en: "meat", note: "neuter" },
      { de: "der Fisch", en: "fish", note: "masculine" },
      { de: "das Gemüse", en: "vegetables", note: "neuter" },
      { de: "die Suppe", en: "soup", note: "feminine" },
      { de: "das Frühstück", en: "breakfast", note: "neuter" },
      { de: "das Mittagessen", en: "lunch", note: "neuter" },
      { de: "das Abendessen", en: "dinner", note: "neuter" },
      { de: "lecker", en: "delicious" },
      { de: "hungrig", en: "hungry" },
      { de: "durstig", en: "thirsty" },
    ],
  },
  {
    id: "home",
    title: "Zuhause",
    titleEn: "Home & Daily Life",
    description: "Rooms, objects, and everyday home words.",
    words: [
      { de: "das Haus", en: "house", note: "neuter" },
      { de: "die Wohnung", en: "apartment", note: "feminine" },
      { de: "die Tür", en: "door", note: "feminine" },
      { de: "das Fenster", en: "window", note: "neuter" },
      { de: "der Tisch", en: "table", note: "masculine" },
      { de: "der Stuhl", en: "chair", note: "masculine" },
      { de: "das Bett", en: "bed", note: "neuter" },
      { de: "die Küche", en: "kitchen", note: "feminine" },
      { de: "das Bad", en: "bathroom", note: "neuter" },
      { de: "das Zimmer", en: "room", note: "neuter" },
      { de: "der Schlüssel", en: "key", note: "masculine" },
      { de: "das Licht", en: "light", note: "neuter" },
      { de: "aufräumen", en: "to tidy up" },
      { de: "kochen", en: "to cook" },
      { de: "waschen", en: "to wash" },
    ],
  },
  {
    id: "travel",
    title: "Reisen & Stadt",
    titleEn: "Travel & City",
    description: "Getting around town and on trips.",
    words: [
      { de: "die Stadt", en: "city", note: "feminine" },
      { de: "der Bahnhof", en: "train station", note: "masculine" },
      { de: "der Zug", en: "train", note: "masculine" },
      { de: "der Bus", en: "bus", note: "masculine" },
      { de: "die Straße", en: "street", note: "feminine" },
      { de: "der Weg", en: "way / path", note: "masculine" },
      { de: "die Karte", en: "map / ticket", note: "feminine" },
      { de: "das Hotel", en: "hotel", note: "neuter" },
      { de: "der Flughafen", en: "airport", note: "masculine" },
      { de: "links", en: "left" },
      { de: "rechts", en: "right" },
      { de: "geradeaus", en: "straight ahead" },
      { de: "weit", en: "far" },
      { de: "nah", en: "near" },
      { de: "Wo ist…?", en: "Where is…?" },
      { de: "Ich suche…", en: "I am looking for…" },
    ],
  },
  {
    id: "time",
    title: "Zeit & Wetter",
    titleEn: "Time & Weather",
    description: "Days, time phrases, and talking about the weather.",
    words: [
      { de: "heute", en: "today" },
      { de: "morgen", en: "tomorrow" },
      { de: "gestern", en: "yesterday" },
      { de: "jetzt", en: "now" },
      { de: "später", en: "later" },
      { de: "die Woche", en: "week", note: "feminine" },
      { de: "der Monat", en: "month", note: "masculine" },
      { de: "das Jahr", en: "year", note: "neuter" },
      { de: "die Uhr", en: "clock / o'clock", note: "feminine" },
      { de: "das Wetter", en: "weather", note: "neuter" },
      { de: "die Sonne", en: "sun", note: "feminine" },
      { de: "der Regen", en: "rain", note: "masculine" },
      { de: "der Wind", en: "wind", note: "masculine" },
      { de: "kalt", en: "cold" },
      { de: "warm", en: "warm" },
      { de: "schön", en: "nice / beautiful" },
    ],
  },
  {
    id: "verbs",
    title: "Wichtige Verben",
    titleEn: "Essential Verbs",
    description: "High-frequency verbs for daily conversation.",
    words: [
      { de: "sein", en: "to be" },
      { de: "haben", en: "to have" },
      { de: "machen", en: "to do / make" },
      { de: "gehen", en: "to go" },
      { de: "kommen", en: "to come" },
      { de: "sehen", en: "to see" },
      { de: "hören", en: "to hear" },
      { de: "sprechen", en: "to speak" },
      { de: "verstehen", en: "to understand" },
      { de: "lernen", en: "to learn" },
      { de: "lesen", en: "to read" },
      { de: "schreiben", en: "to write" },
      { de: "essen", en: "to eat" },
      { de: "trinken", en: "to drink" },
      { de: "schlafen", en: "to sleep" },
      { de: "arbeiten", en: "to work" },
      { de: "wohnen", en: "to live (reside)" },
      { de: "können", en: "can / to be able to" },
      { de: "müssen", en: "must / to have to" },
      { de: "wollen", en: "to want" },
    ],
  },
  {
    id: "colors-numbers",
    title: "Farben & Zahlen",
    titleEn: "Colors & Numbers",
    description: "Basic colors and numbers for shopping and counting.",
    words: [
      { de: "rot", en: "red" },
      { de: "blau", en: "blue" },
      { de: "grün", en: "green" },
      { de: "gelb", en: "yellow" },
      { de: "schwarz", en: "black" },
      { de: "weiß", en: "white" },
      { de: "eins", en: "one" },
      { de: "zwei", en: "two" },
      { de: "drei", en: "three" },
      { de: "vier", en: "four" },
      { de: "fünf", en: "five" },
      { de: "zehn", en: "ten" },
      { de: "zwanzig", en: "twenty" },
      { de: "hundert", en: "hundred" },
      { de: "viel", en: "much / many" },
      { de: "wenig", en: "few / little" },
    ],
  },
];
